// add_wods.js — Erweitert WOD-Datenbank auf 800+
const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, 'data', 'wods.json');
const TYP = { F: 'ForTime', A: 'AMRAP', E: 'EMOM', T: 'Tabata' };
const LVL = { B: 'Beginner', I: 'Intermediate', V: 'Advanced' };

function desc(name, typ, dauer) {
  if (typ === 'ForTime') return `${name} - For Time`;
  if (typ === 'AMRAP')   return `${name} - AMRAP ${dauer} Min`;
  if (typ === 'EMOM')    return `${name} - EMOM ${dauer} Min`;
  if (typ === 'Tabata')  return `${name} - Tabata (20s on / 10s off)`;
  return name;
}
function runden(typ, dauer) {
  if (typ === 'ForTime') return dauer <= 10 ? '1' : dauer <= 20 ? '3' : '5';
  if (typ === 'AMRAP')   return '1';
  if (typ === 'EMOM')    return String(dauer);
  if (typ === 'Tabata')  return '8';
  return '3';
}
function reps(typ) {
  if (typ === 'ForTime') return '21-15-9';
  if (typ === 'AMRAP')   return 'Max Reps';
  if (typ === 'EMOM')    return '10-15 Reps/Min';
  if (typ === 'Tabata')  return '20s on / 10s off';
  return '10';
}
function gewicht(eq) {
  if (!eq || eq.includes('Bodyweight') || eq === '') return 'Bodyweight';
  if (eq.includes('Barbell')) return '60/40';
  if (eq.includes('Kettlebell')) return '24/16';
  if (eq.includes('Dumbbell')) return '22.5/15';
  return 'Bodyweight';
}
function quelle(kat) {
  if (kat === 'Hero WOD') return 'CrossFit HQ';
  if (kat === 'CrossFit Open') return 'CrossFit Open';
  return 'CrossFit Community';
}

// compact: [name, kat, typ, dauer, lvl, equipment, uebungen]
function build(id, c) {
  const [name, kat, t, dauer, l, eq, ueb] = c;
  const typ = TYP[t] || t;
  const schwierigkeit = LVL[l] || l;
  const equipment = Array.isArray(eq) ? eq.join(', ') : eq;
  return {
    id: String(id), name, kategorie: kat, typ,
    beschreibung: desc(name, typ, dauer),
    uebungen: ueb, equipment,
    dauer: String(dauer),
    runden: runden(typ, dauer),
    reps: reps(typ),
    gewicht: gewicht(equipment),
    schwierigkeit,
    skal_leicht: 'Gewicht reduzieren / Ring Rows / weniger Reps',
    skal_schwer: 'Gewicht erhöhen / Chest-to-Bar / mehr Reps',
    quelle: quelle(kat),
  };
}

// ── BLOCK A: Hero WODs ──────────────────────────────────────────────────────
const blockA = [
  ['Arnie', 'Hero WOD', 'F', 20, 'V', 'Barbell, Pull-up Bar', '21 Turkish Get-ups, 50 Pull-ups, 21 Thrusters, 50 Pull-ups, 21 OHS, 50 Pull-ups'],
  ['Brad', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 12 Front Squats, 21 Pull-ups, Run 400m'],
  ['Bradshaw', 'Hero WOD', 'F', 35, 'V', 'Barbell, Jump Rope', '3 Rounds: 22 KB Swings, 22 Box Jumps, 22 Burpees, 22 Wall Balls, 22 DU, 10 Hang Squat Cleans'],
  ['Bull', 'Hero WOD', 'F', 25, 'V', 'Barbell, Pull-up Bar', '21-15-9: Deadlift, Hang Power Clean, Front Squat, Push Jerk, Pull-ups, OHS'],
  ['Coe', 'Hero WOD', 'F', 20, 'I', 'Kettlebell, Pull-up Bar', '3 Rounds: 15 L-Pull-ups, 30 KB Swings, 1 Mile Run'],
  ['Danny', 'Hero WOD', 'A', 20, 'V', 'Barbell, Box', '20 Min AMRAP: 30 Box Jumps, 20 Push Press, 30 Pull-ups'],
  ['Desforges', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 7 Muscle-ups, 155lb Squat Clean, 11 Box Jumps'],
  ['Forrest', 'Hero WOD', 'F', 25, 'V', 'Barbell, Pull-up Bar', '20 L-Pull-ups, 30 Back Extensions, 20 L-Pull-ups, 30 Hip Ext, Run 800m, 21 Burpees'],
  ['Gator', 'Hero WOD', 'F', 30, 'V', 'Kettlebell, Pull-up Bar', '5 Rounds: 10 Pull-ups, 10 Burpees, 10 KB Swings, Run 400m'],
  ['Glen', 'Hero WOD', 'F', 40, 'V', 'Barbell, Pull-up Bar', '30 Clean & Jerks, 1 Mile Run, 10 Rope Climbs, 1 Mile Run, 100 Burpees'],
  ['Hollywood', 'Hero WOD', 'F', 25, 'V', 'Barbell, Box', '5 Rounds: 5 Power Cleans, 10 Front Squats, 5 Jerks, 10 Box Jumps'],
  ['Jake', 'Hero WOD', 'F', 35, 'V', 'Bodyweight', '1 Mile Run, 100 Pull-ups, 200 Push-ups, 300 Air Squats, 1 Mile Run'],
  ['Jason', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '100 Squats, 5 Muscle-ups, 75 Squats, 10 Muscle-ups, 50 Squats, 15 Muscle-ups, 25 Squats, 20 Muscle-ups'],
  ['Khan', 'Hero WOD', 'F', 35, 'V', 'Barbell', '5 Rounds: 15 Deadlifts, 15 Hang Power Cleans, 15 Front Squats, 15 Push Jerks'],
  ['Luce', 'Hero WOD', 'F', 20, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 12 Deadlifts, 9 Hang Power Cleans, 6 Push Jerks, 3 Bar Muscle-ups'],
  ['Mac', 'Hero WOD', 'F', 25, 'I', 'Barbell, Bodyweight', '4 Rounds: 400m Run, 25 OHS, 25 Sit-ups'],
  ['Manion', 'Hero WOD', 'F', 30, 'V', 'Barbell, Bodyweight', '7 Rounds: 1 Mile Run, 29 Back Squats'],
  ['Michael', 'Hero WOD', 'F', 30, 'I', 'Bodyweight', '3 Rounds: 800m Run, 50 Back Ext, 50 Sit-ups'],
  ['Moore', 'Hero WOD', 'F', 25, 'V', 'Pull-up Bar, Barbell', '2 Rounds: 1 Mile Run, 100 Pull-ups, 200 Push-ups, 300 Air Squats'],
  ['Nick', 'Hero WOD', 'F', 30, 'V', 'Barbell, Box', '6 Rounds: 10 Deadlifts, 10 Burpees, 10 Box Jumps, Run 400m'],
  ['Omar', 'Hero WOD', 'F', 25, 'V', 'Barbell, Pull-up Bar', '10 Muscle-ups, 15 Push Press, 20 Box Jumps — 7 Rounds'],
  ['Patrick', 'Hero WOD', 'F', 30, 'V', 'Bodyweight', '5 Rounds: 25 Chin-ups, 50 Push-ups, 50 Sit-ups, 50 Air Squats'],
  ['Pheezy', 'Hero WOD', 'F', 35, 'V', 'Barbell, Box', '6 Rounds: 15 OHS, 15 Box Jumps, 15 Pull-ups, 15 Burpees'],
  ['Tosh', 'Hero WOD', 'F', 30, 'V', 'Barbell, Kettlebell', '5 Rounds: 20 DB Thrusters, 20 KB Swings, 20 Burpees'],
  ['Tucker', 'Hero WOD', 'F', 25, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 10 Deadlifts, 10 Ring Dips, 10 Pull-ups, 10 Sit-ups, Run 400m'],
  ['Tyler', 'Hero WOD', 'F', 30, 'V', 'Bodyweight', '5 Rounds: 7 Muscle-ups, 21 Burpees, 400m Run'],
  ['Van Dam', 'Hero WOD', 'F', 25, 'I', 'Barbell', '4 Rounds: 400m Run, 25 Back Squats, 25 Push-ups'],
  ['Wes', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '20 Min: 5 Power Cleans, 10 Toes-to-Bar, 15 Wall Balls — AMRAP'],
  ['Willy', 'Hero WOD', 'F', 20, 'I', 'Kettlebell, Bodyweight', '5 Rounds: 15 KB Swings, 15 Sit-ups, 15 Box Jumps, Run 400m'],
  ['Rankel', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '6 Rounds: 24 Air Squats, 24 Push-ups, 24 Walking Lunges, 12 Deadlifts, 12 Push Press, 12 Power Cleans'],
  ['Wittman', 'Hero WOD', 'F', 35, 'V', 'Barbell', '7 Rounds: 15 Deadlifts, 15 Hang Power Cleans, 15 Push Jerks'],
  ['Holleyman', 'Hero WOD', 'F', 30, 'V', 'Barbell, Box', '30 Rounds: 5 Wall Balls, 3 HSPU, 1 Power Clean'],
  ['Holbrook', 'Hero WOD', 'F', 35, 'V', 'Barbell, Pull-up Bar', '10 Rounds: 3 Muscle-ups, 5 Power Cleans, 7 Kettlebell Swings'],
  ['Litzen', 'Hero WOD', 'F', 30, 'V', 'Barbell, Bodyweight', '1000m Row, 25 Squat Cleans, 50 Pull-ups, 25 Squat Cleans, 1000m Row'],
  ['Riggins', 'Hero WOD', 'F', 25, 'V', 'Barbell, Bodyweight', '5 Rounds: 10 OHS, 10 Deadlifts, 10 Lateral Burpees'],
  ['Payton', 'Hero WOD', 'F', 30, 'V', 'Barbell, Box', '4 Rounds: 10 Deadlifts, 10 Hang Power Cleans, 10 Front Squats, 10 Push Jerks, 10 Box Jumps'],
  ['Kalsu', 'Hero WOD', 'F', 45, 'V', 'Barbell', 'EMOM 100 Thrusters: 5 Burpees every min start'],
  ['Rahoi', 'Hero WOD', 'A', 12, 'V', 'Box, Barbell', '12 Min AMRAP: 12 Box Jumps, 6 Thruster, 6 Bar-facing Burpees'],
  ['Hammer', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 5 Power Cleans, 10 Front Squats, 5 Push Jerks, 10 Pull-ups, 5 Power Cleans'],
  ['Tisdale', 'Hero WOD', 'F', 25, 'V', 'Barbell, Bodyweight', '5 Rounds: 11 Deadlifts, 2 Rope Climbs, 35 DU'],
  ['Wilson', 'Hero WOD', 'F', 30, 'V', 'Kettlebell, Pull-up Bar', '5 Rounds: 20 Pull-ups, 30 Push-ups, 40 Sit-ups, 50 Squats'],
  ['Ship', 'Hero WOD', 'F', 25, 'V', 'Barbell, Bodyweight', '5 Rounds: 400m Run, 15 OHS, 20 Toes-to-Bar'],
  ['Hicks', 'Hero WOD', 'F', 30, 'V', 'Barbell, Box', '3 Rounds: 800m Run, 50 Deadlifts, 50 Box Jumps'],
  ['Brenton', 'Hero WOD', 'F', 20, 'V', 'Bodyweight', '10 Rounds: 100m Sprint, 10 Push-ups, 10 Sit-ups, 10 Squats'],
  ['Taylor', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '21 OHS, 42 Pull-ups, 15 OHS, 30 Pull-ups, 9 OHS, 18 Pull-ups'],
  ['Scott', 'Hero WOD', 'F', 25, 'I', 'Bodyweight', '5 Rounds: 400m Run, 10 Pull-ups, 25 Push-ups, 25 Air Squats'],
  ['Strong', 'Hero WOD', 'F', 35, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 15 Deadlifts, 12 Hang Power Cleans, 9 Push Jerks, 6 Muscle-ups'],
  ['Thompson', 'Hero WOD', 'F', 30, 'V', 'Barbell', '150 Wall Balls — OHS, Squat Cleans, Thrusters, Back Squats in sets'],
  ['Zimmerman', 'Hero WOD', 'F', 35, 'V', 'Barbell, Pull-up Bar, Box', '11 Rounds: 3 Deadlifts, 6 Burpees, 9 Double-unders, 12 Air Squats'],
  ['Hotshots 19', 'Hero WOD', 'F', 40, 'V', 'Barbell, Bodyweight', '6 Rounds: 30 Air Squats, 19 Power Cleans, 7 Strict Pull-ups, 400m Run'],
  ['Lobo', 'Hero WOD', 'F', 25, 'V', 'Barbell, Kettlebell', '5 Rounds: 10 Power Cleans, 10 KB Swings, 10 Box Jumps, Run 400m'],
  ['Webb', 'Hero WOD', 'F', 30, 'V', 'Barbell, Pull-up Bar', '5 Rounds: 7 Muscle-ups, 5 Squat Cleans, 10 Box Jumps'],
  ['Sweeney', 'Hero WOD', 'F', 25, 'V', 'Barbell', '5 Rounds: 5 Back Squats, 10 Deadlifts, 5 Power Cleans, 10 Push Jerks'],
  ['Gonzalez', 'Hero WOD', 'A', 15, 'V', 'Barbell, Pull-up Bar', '15 Min AMRAP: 5 Pull-ups, 10 Push-ups, 15 Air Squats — weighted vest'],
  ['Price', 'Hero WOD', 'F', 20, 'I', 'Kettlebell, Bodyweight', '4 Rounds: 400m Run, 25 KB Swings, 25 Push-ups'],
];

// ── BLOCK B: EMOM Workouts ───────────────────────────────────────────────────
const blockB = [
  ['EMOM KB Swing Squat', 'EMOM', 'E', 10, 'B', 'Kettlebell', '10 KB Swings, 10 Air Squats'],
  ['EMOM Push Pull Squat', 'EMOM', 'E', 12, 'B', 'Bodyweight', 'Min 1: 10 Push-ups | Min 2: 10 Pull-ups | Min 3: 15 Squats'],
  ['EMOM Barbell Complex', 'EMOM', 'E', 10, 'I', 'Barbell', '3 Power Cleans + 3 Front Squats + 3 Push Jerks'],
  ['EMOM Deadlift Sprint', 'EMOM', 'E', 8, 'I', 'Barbell', '5 Deadlifts + 10 Cal Row'],
  ['EMOM Thruster Pull', 'EMOM', 'E', 10, 'I', 'Barbell, Pull-up Bar', 'Min 1: 7 Thrusters | Min 2: 7 Chest-to-Bar'],
  ['EMOM KB Clean Press', 'EMOM', 'E', 12, 'I', 'Kettlebell', '5 KB Clean & Press each arm'],
  ['EMOM Wall Ball Box', 'EMOM', 'E', 10, 'B', 'Wall Ball, Box', 'Min 1: 15 Wall Balls | Min 2: 10 Box Jumps'],
  ['EMOM Burpee Squat', 'EMOM', 'E', 8, 'B', 'Bodyweight', '5 Burpees + 10 Air Squats'],
  ['EMOM OHS Pull-up', 'EMOM', 'E', 10, 'V', 'Barbell, Pull-up Bar', 'Min 1: 5 OHS | Min 2: 10 Pull-ups'],
  ['EMOM Snatch Balance', 'EMOM', 'E', 8, 'V', 'Barbell', '3 Snatch + 3 Overhead Squats'],
  ['EMOM Row KB', 'EMOM', 'E', 10, 'I', 'Rowing Machine, Kettlebell', 'Min 1: 15 Cal Row | Min 2: 20 KB Swings'],
  ['EMOM T2B Push Press', 'EMOM', 'E', 12, 'I', 'Barbell, Pull-up Bar', 'Min 1: 8 T2B | Min 2: 8 Push Press'],
  ['EMOM Double Under Squat', 'EMOM', 'E', 10, 'I', 'Jump Rope', '30 DU + 10 Air Squats'],
  ['EMOM Cluster', 'EMOM', 'E', 8, 'V', 'Barbell', '5 Clusters (Squat Clean Thruster)'],
  ['EMOM Muscle-up Practice', 'EMOM', 'E', 10, 'V', 'Rings', '3 Ring Muscle-ups'],
  ['EMOM Handstand Push-up', 'EMOM', 'E', 8, 'V', 'Bodyweight', '5 HSPU + 10 Push-ups'],
  ['EMOM KB Snatch', 'EMOM', 'E', 10, 'I', 'Kettlebell', '10 KB Snatches (5 each arm)'],
  ['EMOM Back Squat', 'EMOM', 'E', 10, 'I', 'Barbell', '5 Back Squats at 70%'],
  ['EMOM Clean Jerk', 'EMOM', 'E', 10, 'V', 'Barbell', '1 Clean & Jerk (heavy)'],
  ['EMOM Row Burpee', 'EMOM', 'E', 10, 'I', 'Rowing Machine, Bodyweight', 'Min 1: 12 Cal Row | Min 2: 8 Burpees'],
  ['EMOM Dumbbell Complex', 'EMOM', 'E', 12, 'I', 'Dumbbell', '6 DB Hang Power Cleans + 6 DB Push Press'],
  ['EMOM Pull-up Push-up', 'EMOM', 'E', 10, 'B', 'Pull-up Bar, Bodyweight', 'Min 1: 8 Pull-ups | Min 2: 15 Push-ups'],
  ['EMOM Squat Clean', 'EMOM', 'E', 10, 'V', 'Barbell', '3 Squat Cleans'],
  ['EMOM KB Goblet', 'EMOM', 'E', 10, 'B', 'Kettlebell', '15 Goblet Squats + 10 KB Swings'],
  ['EMOM Bike Abs', 'EMOM', 'E', 12, 'I', 'Assault Bike, Bodyweight', 'Min 1: 12 Cal Bike | Min 2: 15 Sit-ups'],
  ['EMOM Deadlift HSPU', 'EMOM', 'E', 10, 'V', 'Barbell, Bodyweight', 'Min 1: 5 Deadlifts | Min 2: 5 HSPU'],
  ['EMOM Hang Power Clean', 'EMOM', 'E', 10, 'I', 'Barbell', '5 Hang Power Cleans'],
  ['EMOM Jump Rope Squat', 'EMOM', 'E', 8, 'B', 'Jump Rope', '40 Singles + 15 Air Squats'],
  ['EMOM Power Snatch', 'EMOM', 'E', 10, 'V', 'Barbell', '3 Power Snatches'],
  ['EMOM Wall Ball Pull-up', 'EMOM', 'E', 10, 'I', 'Wall Ball, Pull-up Bar', 'Min 1: 15 Wall Balls | Min 2: 8 Pull-ups'],
  ['EMOM KB Turkish', 'EMOM', 'E', 10, 'I', 'Kettlebell', '2 Turkish Get-ups (1 each side)'],
  ['EMOM Box Jump DU', 'EMOM', 'E', 10, 'I', 'Box, Jump Rope', 'Min 1: 10 Box Jumps | Min 2: 30 DU'],
  ['EMOM Front Squat', 'EMOM', 'E', 8, 'I', 'Barbell', '5 Front Squats at 70%'],
  ['EMOM Strict Pull Push', 'EMOM', 'E', 10, 'I', 'Pull-up Bar, Bodyweight', 'Min 1: 5 Strict Pull-ups | Min 2: 10 Dips'],
  ['EMOM Row KB Sprint', 'EMOM', 'E', 16, 'V', 'Rowing Machine, Kettlebell', 'Min 1: 20 Cal Row | Min 2: 15 KB Swings | Min 3: 10 Burpees | Min 4: Rest'],
  ['EMOM Snatch Grip DL', 'EMOM', 'E', 8, 'V', 'Barbell', '5 Snatch Grip Deadlifts'],
  ['EMOM Jumping Lunge', 'EMOM', 'E', 10, 'I', 'Bodyweight', '20 Jumping Lunges + 10 Push-ups'],
  ['EMOM KB Press', 'EMOM', 'E', 10, 'I', 'Kettlebell', '8 KB Strict Press each arm'],
  ['EMOM Thruster Row', 'EMOM', 'E', 12, 'I', 'Barbell, Rowing Machine', 'Min 1: 7 Thrusters | Min 2: 12 Cal Row'],
  ['EMOM Pistol Squat', 'EMOM', 'E', 10, 'V', 'Bodyweight', '5 Pistol Squats each leg'],
  ['EMOM DB Snatch', 'EMOM', 'E', 10, 'I', 'Dumbbell', '10 DB Snatches (5 each arm)'],
  ['EMOM Clean Complex', 'EMOM', 'E', 12, 'V', 'Barbell', '2 Hang Power Clean + 2 Power Clean + 2 Clean'],
  ['EMOM T2B KB', 'EMOM', 'E', 10, 'I', 'Pull-up Bar, Kettlebell', 'Min 1: 10 T2B | Min 2: 15 KB Swings'],
  ['EMOM Bike Row', 'EMOM', 'E', 14, 'I', 'Assault Bike, Rowing Machine', 'Min 1-7: 10 Cal Bike | Min 8-14: 12 Cal Row'],
  ['EMOM Strict HSPU', 'EMOM', 'E', 8, 'V', 'Bodyweight', '5 Strict HSPU'],
  ['EMOM Plank Complex', 'EMOM', 'E', 10, 'B', 'Bodyweight', '30s Plank + 10 Mountain Climbers'],
  ['EMOM Squat Snatch', 'EMOM', 'E', 10, 'V', 'Barbell', '2 Squat Snatches'],
  ['EMOM Air Squat Sprint', 'EMOM', 'E', 8, 'B', 'Bodyweight', '20 Air Squats'],
  ['EMOM V-up KB', 'EMOM', 'E', 10, 'I', 'Kettlebell', 'Min 1: 15 V-ups | Min 2: 20 KB Swings'],
  ['EMOM Lunge KB Press', 'EMOM', 'E', 10, 'I', 'Kettlebell', '10 Walking Lunges + 8 KB Press'],
  ['EMOM Bike Burpee', 'EMOM', 'E', 12, 'I', 'Assault Bike, Bodyweight', 'Min 1: 10 Cal Bike | Min 2: 8 Burpees'],
  ['EMOM Ring Row Push', 'EMOM', 'E', 10, 'B', 'Rings, Bodyweight', 'Min 1: 10 Ring Rows | Min 2: 15 Push-ups'],
  ['EMOM KB Deadlift Row', 'EMOM', 'E', 10, 'I', 'Kettlebell', '10 KB Deadlifts + 10 KB Rows each side'],
  ['EMOM Jump Squat', 'EMOM', 'E', 8, 'B', 'Bodyweight', '15 Jump Squats'],
  ['EMOM Hang Snatch', 'EMOM', 'E', 10, 'V', 'Barbell', '3 Hang Snatches'],
  ['EMOM GHD Sit-up', 'EMOM', 'E', 10, 'I', 'GHD Machine', '15 GHD Sit-ups'],
  ['EMOM Back Extension', 'EMOM', 'E', 10, 'B', 'GHD Machine', '15 Back Extensions'],
  ['EMOM KB Windmill', 'EMOM', 'E', 10, 'I', 'Kettlebell', '5 Windmills each side'],
  ['EMOM Sumo DL High Pull', 'EMOM', 'E', 10, 'I', 'Barbell', '10 Sumo Deadlift High Pulls'],
  ['EMOM Box Step KB', 'EMOM', 'E', 12, 'B', 'Box, Kettlebell', 'Min 1: 10 Box Step-ups | Min 2: 15 KB Swings'],
  ['EMOM Ring Push-up', 'EMOM', 'E', 8, 'I', 'Rings', '15 Ring Push-ups'],
  ['EMOM Overhead Walk', 'EMOM', 'E', 10, 'I', 'Barbell', '20m Overhead Carry each arm'],
  ['EMOM Power Clean T2B', 'EMOM', 'E', 10, 'V', 'Barbell, Pull-up Bar', 'Min 1: 5 Power Cleans | Min 2: 8 T2B'],
  ['EMOM Ski Row Bike', 'EMOM', 'E', 15, 'I', 'Ski Erg, Rowing Machine, Assault Bike', 'Min 1: 15 Cal Ski | Min 2: 15 Cal Row | Min 3: 15 Cal Bike'],
  ['EMOM Dip Lunge', 'EMOM', 'E', 10, 'B', 'Pull-up Bar, Bodyweight', 'Min 1: 10 Dips | Min 2: 20 Lunges'],
  ['EMOM Bear Complex', 'EMOM', 'E', 7, 'V', 'Barbell', '1 Bear Complex (PC + FS + PP + BS + PP)'],
  ['EMOM KB Flow', 'EMOM', 'E', 10, 'I', 'Kettlebell', '5 KB Clean + 5 KB Press + 5 KB Squat (each arm)'],
  ['EMOM Hollow Body', 'EMOM', 'E', 8, 'B', 'Bodyweight', '30s Hollow Body Hold'],
  ['EMOM Broad Jump Burpee', 'EMOM', 'E', 8, 'I', 'Bodyweight', '5 Broad Jumps + 5 Burpees'],
  ['EMOM Sandbag Clean', 'EMOM', 'E', 10, 'I', 'Sandbag', '5 Sandbag Cleans + 5 Shoulder-to-OH'],
  ['EMOM KB Farmers Carry', 'EMOM', 'E', 10, 'I', 'Kettlebell', '40m KB Farmers Carry + 10 KB Swings'],
  ['EMOM Push Jerk', 'EMOM', 'E', 8, 'I', 'Barbell', '5 Push Jerks at 70%'],
  ['EMOM Assault Row Sit', 'EMOM', 'E', 12, 'I', 'Assault Bike, Rowing Machine, Bodyweight', '4 Rounds: 10 Cal Bike, 10 Cal Row, 10 Sit-ups'],
  ['EMOM Deficit Push-up', 'EMOM', 'E', 8, 'I', 'Bodyweight', '10 Deficit Push-ups'],
  ['EMOM Pause Squat', 'EMOM', 'E', 8, 'I', 'Barbell', '3 Pause Back Squats (3s hold)'],
  ['EMOM KB Complex 3', 'EMOM', 'E', 10, 'I', 'Kettlebell', '5 KB Swings + 5 KB Cleans + 5 KB Press (each arm)'],
  ['EMOM Bike Sprint', 'EMOM', 'E', 10, 'I', 'Assault Bike', '10 Cal Assault Bike sprint'],
  ['EMOM T2B DU', 'EMOM', 'E', 10, 'I', 'Pull-up Bar, Jump Rope', 'Min 1: 10 T2B | Min 2: 30 DU'],
  ['EMOM Hang Clean', 'EMOM', 'E', 10, 'V', 'Barbell', '3 Hang Squat Cleans'],
  ['EMOM Wall Sit KB', 'EMOM', 'E', 8, 'B', 'Kettlebell, Bodyweight', '30s Wall Sit + 10 KB Swings'],
  ['EMOM Ring Muscle-up Dip', 'EMOM', 'E', 10, 'V', 'Rings', 'Min 1: 3 Ring Muscle-ups | Min 2: 10 Ring Dips'],
  ['EMOM Bar Muscle-up', 'EMOM', 'E', 8, 'V', 'Pull-up Bar', '3 Bar Muscle-ups'],
  ['EMOM KB Halo', 'EMOM', 'E', 8, 'B', 'Kettlebell', '8 KB Halos + 10 KB Swings'],
  ['EMOM Thruster Complex', 'EMOM', 'E', 10, 'V', 'Barbell', '3 Thrusters (heavy)'],
  ['EMOM Push-up Squat Run', 'EMOM', 'E', 12, 'I', 'Bodyweight', 'Min 1: 15 Push-ups | Min 2: 20 Squats | Min 3: 200m Run'],
  ['EMOM Ski Burpee', 'EMOM', 'E', 10, 'I', 'Ski Erg, Bodyweight', 'Min 1: 15 Cal Ski | Min 2: 8 Burpees'],
  ['EMOM RDL Row', 'EMOM', 'E', 10, 'I', 'Barbell', '8 Romanian Deadlifts + 8 Bent-over Rows'],
  ['EMOM Seated Press', 'EMOM', 'E', 8, 'I', 'Dumbbell', '10 Seated DB Press'],
  ['EMOM DU Sit-up', 'EMOM', 'E', 10, 'B', 'Jump Rope, Bodyweight', 'Min 1: 30 DU | Min 2: 20 Sit-ups'],
  ['EMOM Step-up Press', 'EMOM', 'E', 10, 'B', 'Box, Dumbbell', '10 Box Step-ups + 10 DB Press'],
  ['EMOM Jerk Drive', 'EMOM', 'E', 8, 'V', 'Barbell', '3 Split Jerks'],
  ['EMOM Hip Thrust', 'EMOM', 'E', 8, 'B', 'Barbell, Bodyweight', '10 Hip Thrusts'],
  ['EMOM KB Single Leg', 'EMOM', 'E', 10, 'I', 'Kettlebell', '8 Single-leg KB Deadlifts each leg'],
  ['EMOM Assault Bike Max', 'EMOM', 'E', 5, 'V', 'Assault Bike', 'Max Cal Assault Bike each minute'],
  ['EMOM Overhead Squat', 'EMOM', 'E', 10, 'V', 'Barbell', '5 Overhead Squats'],
  ['EMOM Push-up Plank', 'EMOM', 'E', 8, 'B', 'Bodyweight', '10 Push-ups + 20s Plank Hold'],
  ['EMOM Box Burpee KB', 'EMOM', 'E', 12, 'I', 'Box, Kettlebell, Bodyweight', 'Min 1: 8 Box Jumps | Min 2: 15 KB Swings | Min 3: 5 Burpees'],
  ['EMOM Banded Pull-apart', 'EMOM', 'E', 8, 'B', 'Resistance Band', '15 Band Pull-aparts + 10 OH Band Press'],
];

// ── BLOCK C: Tabata Workouts ─────────────────────────────────────────────────
const blockC = [
  ['Tabata Air Squat', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Air Squats'],
  ['Tabata Push-up', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Push-ups'],
  ['Tabata Burpee', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Burpees'],
  ['Tabata KB Swing', 'Tabata', 'T', 4, 'I', 'Kettlebell', 'KB Swings'],
  ['Tabata Sit-up', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Sit-ups'],
  ['Tabata Row', 'Tabata', 'T', 4, 'I', 'Rowing Machine', 'Row (Cals)'],
  ['Tabata Wall Ball', 'Tabata', 'T', 4, 'I', 'Wall Ball', 'Wall Balls'],
  ['Tabata Box Jump', 'Tabata', 'T', 4, 'I', 'Box', 'Box Jumps'],
  ['Tabata Double Under', 'Tabata', 'T', 4, 'I', 'Jump Rope', 'Double Unders'],
  ['Tabata Thruster', 'Tabata', 'T', 4, 'V', 'Barbell', 'Thrusters'],
  ['Tabata Pull-up', 'Tabata', 'T', 4, 'I', 'Pull-up Bar', 'Pull-ups'],
  ['Tabata Ring Row', 'Tabata', 'T', 4, 'B', 'Rings', 'Ring Rows'],
  ['Tabata Mountain Climber', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Mountain Climbers'],
  ['Tabata Lunge', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Alternating Lunges'],
  ['Tabata Jumping Lunge', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Jumping Lunges'],
  ['Tabata KB Goblet Squat', 'Tabata', 'T', 4, 'I', 'Kettlebell', 'KB Goblet Squats'],
  ['Tabata DB Snatch', 'Tabata', 'T', 4, 'I', 'Dumbbell', 'DB Snatches (alternating)'],
  ['Tabata Assault Bike', 'Tabata', 'T', 4, 'V', 'Assault Bike', 'Max Cal Assault Bike'],
  ['Tabata V-up', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'V-ups'],
  ['Tabata T2B', 'Tabata', 'T', 4, 'I', 'Pull-up Bar', 'Toes-to-Bar'],
  ['Tabata HSPU', 'Tabata', 'T', 4, 'V', 'Bodyweight', 'Handstand Push-ups'],
  ['Tabata Ring Dip', 'Tabata', 'T', 4, 'V', 'Rings', 'Ring Dips'],
  ['Tabata Hollow Rock', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Hollow Rocks'],
  ['Tabata Push-up Squat', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Push-up + Air Squat combo'],
  ['Tabata KB Snatch', 'Tabata', 'T', 4, 'I', 'Kettlebell', 'KB Snatches (alternating arms)'],
  ['Tabata Jump Squat', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Jump Squats'],
  ['Tabata Dip', 'Tabata', 'T', 4, 'I', 'Pull-up Bar', 'Bar Dips'],
  ['Tabata Wall Sit', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Wall Sit hold'],
  ['Tabata Broad Jump', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Broad Jumps'],
  ['Tabata Ski Erg', 'Tabata', 'T', 4, 'I', 'Ski Erg', 'Ski Erg Max Cals'],
  ['Tabata Plank', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Plank Hold'],
  ['Tabata Superman', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Superman Hold / Back Extensions'],
  ['Tabata Glute Bridge', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Glute Bridge'],
  ['Tabata High Knees', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'High Knees'],
  ['Tabata Push-up Burpee', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Push-up + Burpee (alt)'],
  ['Tabata Squat Jump Sit-up', 'Tabata', 'T', 4, 'I', 'Bodyweight', 'Alt: Jump Squats & Sit-ups'],
  ['Tabata DB Thruster', 'Tabata', 'T', 4, 'I', 'Dumbbell', 'DB Thrusters'],
  ['Tabata KB Deadlift', 'Tabata', 'T', 4, 'B', 'Kettlebell', 'KB Deadlifts'],
  ['Tabata Ring Push-up', 'Tabata', 'T', 4, 'I', 'Rings', 'Ring Push-ups'],
  ['Tabata Box Step-up', 'Tabata', 'T', 4, 'B', 'Box', 'Box Step-ups'],
  ['Tabata Power Clean', 'Tabata', 'T', 4, 'V', 'Barbell', 'Power Cleans (light)'],
  ['Tabata Strict Press', 'Tabata', 'T', 4, 'I', 'Barbell', 'Strict Press (light)'],
  ['Tabata Hang Power Clean', 'Tabata', 'T', 4, 'I', 'Barbell', 'Hang Power Cleans'],
  ['Tabata DU Squat', 'Tabata', 'T', 4, 'I', 'Jump Rope', '20s DU / 10s Air Squat'],
  ['Tabata KB Row', 'Tabata', 'T', 4, 'I', 'Kettlebell', 'KB Bent-over Rows'],
  ['Tabata Jumping Jack', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Jumping Jacks'],
  ['Tabata Sprint', 'Tabata', 'T', 4, 'I', 'Bodyweight', '20s Sprint / 10s Rest'],
  ['Tabata Deadlift', 'Tabata', 'T', 4, 'I', 'Barbell', 'Deadlifts (moderate weight)'],
  ['Tabata Push-up Pull-up', 'Tabata', 'T', 4, 'I', 'Pull-up Bar, Bodyweight', 'Alt: Push-ups / Pull-ups'],
  ['Tabata Step-up Burpee', 'Tabata', 'T', 4, 'I', 'Box, Bodyweight', 'Alt: Box Step-ups / Burpees'],
  ['Tabata KB Press Row', 'Tabata', 'T', 4, 'I', 'Kettlebell', 'Alt: KB Press / KB Row'],
  ['Tabata Squat Jump Pull', 'Tabata', 'T', 4, 'I', 'Pull-up Bar, Bodyweight', 'Alt: Jump Squats / Pull-ups'],
  ['Tabata Full Body 1', 'Tabata', 'T', 16, 'I', 'Bodyweight', '4 Exercises: Squats, Push-ups, Sit-ups, Burpees — 2 rounds each'],
  ['Tabata Full Body 2', 'Tabata', 'T', 16, 'V', 'Barbell, Pull-up Bar', '4 Exercises: Thrusters, Pull-ups, Deadlifts, Burpees'],
  ['Tabata KB Full', 'Tabata', 'T', 12, 'I', 'Kettlebell', '3 Exercises: KB Swings, KB Goblet Squat, KB Push Press'],
  ['Tabata Cardio Blast', 'Tabata', 'T', 8, 'I', 'Bodyweight', 'Alt: Burpees / Mountain Climbers'],
  ['Tabata Core 1', 'Tabata', 'T', 8, 'B', 'Bodyweight', 'Alt: Sit-ups / Hollow Rocks'],
  ['Tabata Core 2', 'Tabata', 'T', 8, 'I', 'Bodyweight', 'Alt: V-ups / Plank'],
  ['Tabata Legs 1', 'Tabata', 'T', 8, 'B', 'Bodyweight', 'Alt: Air Squats / Lunges'],
  ['Tabata Legs 2', 'Tabata', 'T', 8, 'I', 'Bodyweight', 'Alt: Jump Squats / Jumping Lunges'],
  ['Tabata Upper Body', 'Tabata', 'T', 8, 'I', 'Pull-up Bar, Bodyweight', 'Alt: Push-ups / Ring Rows'],
  ['Tabata Bike Row', 'Tabata', 'T', 8, 'V', 'Assault Bike, Rowing Machine', 'Alt: Max Cal Bike / Max Cal Row'],
  ['Tabata Snatch Squat', 'Tabata', 'T', 4, 'V', 'Barbell', 'Power Snatch + OHS combo'],
  ['Tabata Bear Crawl', 'Tabata', 'T', 4, 'B', 'Bodyweight', 'Bear Crawl 20m / Rest'],
];

// ── BLOCK D: Bodyweight / Home WODs ─────────────────────────────────────────
const blockD = [
  ['Push Pull 21-15-9', 'HomeWOD', 'F', 12, 'I', 'Bodyweight', '21-15-9: Pull-ups, Push-ups'],
  ['Bodyweight 100s', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', '100 Pull-ups, 100 Push-ups, 100 Sit-ups, 100 Squats — partition as needed'],
  ['AMRAP Burpee Squat 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 10 Burpees, 20 Air Squats'],
  ['AMRAP Push Lunge 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 12 Push-ups, 12 Lunges each leg'],
  ['Chipper 50-40-30-20-10', 'HomeWOD', 'F', 25, 'I', 'Bodyweight', '50 Jumping Jacks, 40 Sit-ups, 30 Squats, 20 Push-ups, 10 Burpees'],
  ['AMRAP Sit Squat Lunge 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 15 Sit-ups, 15 Squats, 15 Lunges'],
  ['10 Rounds Push Squat', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '10 Rounds: 10 Push-ups, 10 Squats'],
  ['AMRAP Burpee Pull 8', 'HomeWOD', 'A', 8, 'I', 'Pull-up Bar', '8 Min AMRAP: 5 Burpees, 5 Pull-ups'],
  ['Death by Push-up', 'HomeWOD', 'E', 20, 'I', 'Bodyweight', 'Min 1: 1 Push-up, min 2: 2, continue until failure'],
  ['AMRAP Mountain Climber Squat 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 20 Mountain Climbers, 15 Air Squats'],
  ['Bodyweight Ladder 1-10', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '1-10 Ladder: Push-ups + Sit-ups'],
  ['AMRAP V-up Push Burpee 12', 'HomeWOD', 'A', 12, 'I', 'Bodyweight', '12 Min AMRAP: 10 V-ups, 10 Push-ups, 5 Burpees'],
  ['Sprint Squat 8 Rounds', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '8 Rounds: 200m Sprint, 20 Air Squats'],
  ['AMRAP Lunge Sit Jump 20', 'HomeWOD', 'A', 20, 'B', 'Bodyweight', '20 Min AMRAP: 20 Lunges, 20 Sit-ups, 20 Jump Squats'],
  ['Bodyweight Cindy', 'HomeWOD', 'A', 20, 'I', 'Pull-up Bar, Bodyweight', '20 Min AMRAP: 5 Pull-ups, 10 Push-ups, 15 Squats'],
  ['Push Sit Run Chipper', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', '100 Push-ups, 100 Sit-ups, 1 Mile Run'],
  ['AMRAP Burpee Jump 15', 'HomeWOD', 'A', 15, 'I', 'Bodyweight', '15 Min AMRAP: 8 Burpees, 12 Jump Squats'],
  ['Full Body Ladder 5-10-15', 'HomeWOD', 'F', 18, 'I', 'Bodyweight', '5 Rounds: 5 Pull-ups, 10 Push-ups, 15 Squats, 20 Sit-ups'],
  ['AMRAP HC Plank Push 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 20 HC, 30s Plank, 10 Push-ups'],
  ['Bodyweight 300', 'HomeWOD', 'F', 30, 'V', 'Pull-up Bar, Bodyweight', '25 Pull-ups, 50 DL, 50 Push-ups, 50 Box Jumps, 50 Floor Wipers, 50 Clean & Press, 25 Pull-ups'],
  ['AMRAP Burpee Sit Squat 20', 'HomeWOD', 'A', 20, 'B', 'Bodyweight', '20 Min AMRAP: 5 Burpees, 10 Sit-ups, 15 Squats'],
  ['10 Rounds Pull Push Sit', 'HomeWOD', 'F', 20, 'I', 'Pull-up Bar, Bodyweight', '10 Rounds: 5 Pull-ups, 10 Push-ups, 15 Sit-ups'],
  ['AMRAP Jump Lunge V-up 12', 'HomeWOD', 'A', 12, 'I', 'Bodyweight', '12 Min AMRAP: 15 Jump Squats, 15 Lunges, 10 V-ups'],
  ['Tabata Something Bodyweight', 'HomeWOD', 'T', 16, 'I', 'Bodyweight', '4 Exercises Tabata: Squats, Push-ups, Sit-ups, Burpees'],
  ['Push-up Pyramid 1-10-1', 'HomeWOD', 'F', 12, 'I', 'Bodyweight', 'Pyramid up and down: 1-2-3...10-9...1 Push-ups'],
  ['AMRAP Climb Push Squat 15', 'HomeWOD', 'A', 15, 'I', 'Bodyweight', '15 Min AMRAP: 15 Mountain Climbers, 10 Push-ups, 20 Squats'],
  ['Sprint Lunge Push 6 Rounds', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '6 Rounds: 200m Sprint, 15 Lunges, 15 Push-ups'],
  ['AMRAP Burpee HC V-up 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 8 Burpees, 20 HC, 10 V-ups'],
  ['Bodyweight DT', 'HomeWOD', 'F', 15, 'V', 'Pull-up Bar, Bodyweight', '5 Rounds: 12 HSPU, 9 Strict Pull-ups, 6 Muscle-ups'],
  ['AMRAP Double Push Squat 20', 'HomeWOD', 'A', 20, 'I', 'Bodyweight', '20 Min AMRAP: 20 Push-ups, 30 Squats'],
  ['100 Burpee Challenge', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '100 Burpees for time'],
  ['AMRAP Sit Lunge Push 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 12 Sit-ups, 12 Lunges, 12 Push-ups'],
  ['Bodyweight Tabata 4x', 'HomeWOD', 'T', 16, 'B', 'Bodyweight', 'Tabata: Push-ups / Squats / Sit-ups / Burpees'],
  ['8 Rounds Sprint Squat Sit', 'HomeWOD', 'F', 16, 'I', 'Bodyweight', '8 Rounds: 100m Sprint, 15 Squats, 15 Sit-ups'],
  ['AMRAP Burpee Pull Jump 15', 'HomeWOD', 'A', 15, 'V', 'Pull-up Bar, Bodyweight', '15 Min AMRAP: 5 Burpees, 5 Pull-ups, 10 Jump Squats'],
  ['Push-up Sit-up 21-15-9', 'HomeWOD', 'F', 8, 'B', 'Bodyweight', '21-15-9: Push-ups, Sit-ups'],
  ['AMRAP HC Squat Lunge 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 20 HC, 20 Squats, 20 Lunges'],
  ['Box Jump Burpee Sit 5 Rounds', 'HomeWOD', 'F', 15, 'I', 'Box, Bodyweight', '5 Rounds: 15 Box Jumps, 10 Burpees, 20 Sit-ups'],
  ['AMRAP Pull Push Sit Squat 20', 'HomeWOD', 'A', 20, 'I', 'Pull-up Bar, Bodyweight', '20 Min AMRAP: 5 Pull-ups, 10 Push-ups, 15 Sit-ups, 20 Squats'],
  ['Bodyweight Hurricane', 'HomeWOD', 'F', 25, 'V', 'Bodyweight', '3 Rounds: 400m Sprint, 20 Burpees, 30 Push-ups, 40 Sit-ups, 50 Squats'],
  ['AMRAP Plank Push V 8', 'HomeWOD', 'A', 8, 'B', 'Bodyweight', '8 Min AMRAP: 30s Plank, 10 Push-ups, 10 V-ups'],
  ['10x10 Push Pull', 'HomeWOD', 'F', 18, 'I', 'Pull-up Bar, Bodyweight', '10 Sets of 10 Push-ups + 10 Pull-ups'],
  ['AMRAP Jump HC Squat 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 15 Jump Squats, 20 HC, 15 Sit-ups'],
  ['5x5 Sprint Burpee', 'HomeWOD', 'F', 12, 'I', 'Bodyweight', '5 Rounds: 100m Sprint, 5 Burpees, 5 Burpees again'],
  ['AMRAP Lunge Push Jump 20', 'HomeWOD', 'A', 20, 'I', 'Bodyweight', '20 Min AMRAP: 20 Lunges, 15 Push-ups, 15 Jump Squats'],
  ['Bodyweight Baseline', 'HomeWOD', 'F', 8, 'B', 'Bodyweight', '500m Row (or 400m Run), 40 Squats, 30 Sit-ups, 20 Push-ups, 10 Pull-ups'],
  ['AMRAP Burpee Jump Sit 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 5 Burpees, 10 Jump Squats, 15 Sit-ups'],
  ['Push Squat Run 4 Miles', 'HomeWOD', 'F', 35, 'I', 'Bodyweight', '1 Mile Run, 100 Push-ups, 1 Mile Run, 100 Squats'],
  ['AMRAP HC Lunge Jump 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 20 HC, 20 Lunges, 20 Jump Squats'],
  ['Death by Burpee', 'HomeWOD', 'E', 15, 'I', 'Bodyweight', 'Min 1: 1 Burpee, min 2: 2, continue until failure'],
  ['AMRAP Push Pull Squat 20', 'HomeWOD', 'A', 20, 'I', 'Pull-up Bar, Bodyweight', '20 Min AMRAP: 10 Push-ups, 5 Pull-ups, 20 Squats'],
  ['Bodyweight Pyramid Full', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', 'Pyramid 1-10: Burpees / 10-1: Squats'],
  ['AMRAP Sit HC Push 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 15 Sit-ups, 20 HC, 15 Push-ups'],
  ['Run Push Squat 5k', 'HomeWOD', 'F', 30, 'I', 'Bodyweight', '5k Run with 50 Push-ups and 50 Squats at 2.5k mark'],
  ['AMRAP Burpee Lunge V 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 8 Burpees, 16 Lunges, 10 V-ups'],
  ['50-40-30-20-10 Bodyweight', 'HomeWOD', 'F', 25, 'I', 'Bodyweight', '50-40-30-20-10 of each: Squats, Push-ups, Sit-ups'],
  ['AMRAP Pull Push Lunge 15', 'HomeWOD', 'A', 15, 'I', 'Pull-up Bar, Bodyweight', '15 Min AMRAP: 5 Pull-ups, 10 Push-ups, 20 Lunges'],
  ['Jump Squat Sit Sprint 6', 'HomeWOD', 'F', 14, 'I', 'Bodyweight', '6 Rounds: 20 Jump Squats, 20 Sit-ups, 200m Sprint'],
  ['AMRAP HC Climb Squat 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 20 HC, 20 Mountain Climbers, 15 Squats'],
  ['Bodyweight Gauntlet', 'HomeWOD', 'F', 30, 'V', 'Pull-up Bar, Bodyweight', '10 Pull-ups, 20 Push-ups, 30 Sit-ups, 40 Squats — 5 Rounds'],
  ['AMRAP Burpee Sit Pull 12', 'HomeWOD', 'A', 12, 'I', 'Pull-up Bar, Bodyweight', '12 Min AMRAP: 5 Burpees, 10 Sit-ups, 5 Pull-ups'],
  ['Push-up Lunge 5 Rounds', 'HomeWOD', 'F', 12, 'B', 'Bodyweight', '5 Rounds: 20 Push-ups, 20 Alternating Lunges'],
  ['AMRAP V-up Lunge Sprint 10', 'HomeWOD', 'A', 10, 'I', 'Bodyweight', '10 Min AMRAP: 10 V-ups, 20 Lunges, 100m Sprint'],
  ['400m Run + 50 Each', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', '3 Rounds: 400m Run, 50 Squats, 50 Sit-ups'],
  ['AMRAP Push Jump HC 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 15 Push-ups, 15 Jump Squats, 20 HC'],
  ['5 Rounds Core Power', 'HomeWOD', 'F', 20, 'I', 'Pull-up Bar, Bodyweight', '5 Rounds: 10 Pull-ups, 10 HSPU, 20 Sit-ups, 20 Squats'],
  ['AMRAP Burpee Pull Squat 20', 'HomeWOD', 'A', 20, 'V', 'Pull-up Bar, Bodyweight', '20 Min AMRAP: 10 Burpees, 10 Pull-ups, 20 Squats'],
  ['Bodyweight Fran Alt', 'HomeWOD', 'F', 8, 'I', 'Pull-up Bar, Bodyweight', '21-15-9: Jump Squats, Pull-ups'],
  ['AMRAP Lunge Push Sit 20', 'HomeWOD', 'A', 20, 'B', 'Bodyweight', '20 Min AMRAP: 30 Lunges, 20 Push-ups, 20 Sit-ups'],
  ['Bodyweight 400', 'HomeWOD', 'F', 25, 'V', 'Bodyweight', '400 Reps: 100 Push-ups, 100 Sit-ups, 100 Squats, 100 Lunges'],
  ['AMRAP Jump HC Lunge 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 20 Jump Squats, 20 HC, 20 Lunges'],
  ['10 Rounds Sit Push Sprint', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', '10 Rounds: 15 Sit-ups, 10 Push-ups, 100m Sprint'],
  ['AMRAP Pull Burpee 10', 'HomeWOD', 'A', 10, 'V', 'Pull-up Bar, Bodyweight', '10 Min AMRAP: 10 Pull-ups, 5 Burpees'],
  ['Triple 3', 'HomeWOD', 'F', 30, 'V', 'Pull-up Bar, Bodyweight', '3 Mile Run, 300 Push-ups, 300 Squats — partition as needed'],
  ['AMRAP HC Sit Squat Jump 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 20 HC, 15 Sit-ups, 15 Squats, 10 Jump Squats'],
  ['Push Pull Squat 5x5', 'HomeWOD', 'F', 15, 'I', 'Pull-up Bar, Bodyweight', '5 Rounds: 5 Pull-ups, 10 Push-ups, 20 Squats'],
  ['AMRAP Burpee V Lunge 12', 'HomeWOD', 'A', 12, 'I', 'Bodyweight', '12 Min AMRAP: 6 Burpees, 12 V-ups, 18 Lunges'],
  ['Bodyweight Total', 'HomeWOD', 'F', 20, 'I', 'Bodyweight', '50 Burpees, 100 Push-ups, 150 Squats, 200 Sit-ups'],
  ['AMRAP Squat Push V 20', 'HomeWOD', 'A', 20, 'B', 'Bodyweight', '20 Min AMRAP: 20 Squats, 15 Push-ups, 10 V-ups'],
  ['Bodyweight SWOD', 'HomeWOD', 'F', 12, 'I', 'Bodyweight', '21-15-9: Squat Jumps, Push-ups, V-ups'],
  ['AMRAP HC Squat Sprint 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 20 HC, 20 Squats, 100m Sprint'],
  ['5 Rounds Bodyweight Classic', 'HomeWOD', 'F', 18, 'I', 'Pull-up Bar, Bodyweight', '5 Rounds: 20 Pull-ups, 30 Push-ups, 40 Sit-ups, 50 Squats'],
];

// ── BLOCK E: Strength & Barbell WODs ────────────────────────────────────────
const blockE = [
  ['Barbell Complex A', 'Other Benchmark', 'F', 15, 'I', 'Barbell', '5 Rounds: 5 Deadlifts, 5 Hang Power Cleans, 5 Front Squats, 5 Push Press'],
  ['Strength Chipper', 'Other Benchmark', 'F', 20, 'V', 'Barbell', '30 Deadlifts, 20 Power Cleans, 15 Front Squats, 10 Push Jerks, 5 Squat Cleans'],
  ['Bear Complex 5x5', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Sets of 7 Bear Complex (PC+FS+PP+BS+PP)'],
  ['Deadlift 21-15-9', 'Other Benchmark', 'F', 12, 'I', 'Barbell, Pull-up Bar', '21-15-9: Deadlifts, Pull-ups'],
  ['Push Jerk Complex', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Rounds: 5 Push Jerks, 5 Split Jerks, 5 Push Press'],
  ['Front Squat + T2B', 'Other Benchmark', 'F', 12, 'I', 'Barbell, Pull-up Bar', '5 Rounds: 5 Front Squats, 10 T2B'],
  ['Squat Clean Thruster', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '3 Rounds: 10 Squat Cleans, 10 Thrusters'],
  ['Power Clean AMRAP 10', 'Other Benchmark', 'A', 10, 'I', 'Barbell', '10 Min AMRAP: 5 Power Cleans, 10 Burpees'],
  ['Snatch Balance 5x3', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Sets of 3 Snatch Balance'],
  ['OHS Complex', 'Other Benchmark', 'F', 12, 'V', 'Barbell', '5 Sets: 5 OHS + 5 Snatch Balance'],
  ['5×3 Back Squat', 'Other Benchmark', 'F', 20, 'I', 'Barbell', '5 Sets of 3 Back Squats (heavy)'],
  ['Barbell Cycling', 'Other Benchmark', 'A', 8, 'V', 'Barbell', '8 Min AMRAP: 3 Squat Cleans + 3 Jerks'],
  ['Snatch Ladder', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '10-8-6-4-2: Power Snatches (increasing weight)'],
  ['Clean & Jerk AMRAP', 'Other Benchmark', 'A', 7, 'V', 'Barbell', '7 Min AMRAP: 1 Clean & Jerk (heavy)'],
  ['Deadlift Density', 'Other Benchmark', 'F', 10, 'I', 'Barbell', '10 Min: Max Deadlifts at 80% 1RM'],
  ['Push Press + Row', 'Other Benchmark', 'F', 12, 'I', 'Barbell, Rowing Machine', '5 Rounds: 10 Push Press, 250m Row'],
  ['Overhead Complex', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Sets: 3 Push Press + 3 Push Jerk + 3 Split Jerk'],
  ['Front Squat AMRAP', 'Other Benchmark', 'A', 10, 'I', 'Barbell', '10 Min AMRAP: 5 Front Squats, 5 Pull-ups'],
  ['Hang Power Snatch Complex', 'Other Benchmark', 'F', 12, 'V', 'Barbell', '5 Sets: 3 HPS + 3 OHS'],
  ['Thrusters 30-20-10', 'Other Benchmark', 'F', 12, 'I', 'Barbell', '30-20-10: Thrusters, Burpees'],
  ['Squat Clean Ladder', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '1-2-3-4-5: Squat Cleans (add weight each round)'],
  ['Power Snatch Density', 'Other Benchmark', 'F', 12, 'V', 'Barbell', '12 Min: Every 90s — 3 Power Snatches'],
  ['AMRAP Clean Pull Squat', 'Other Benchmark', 'A', 12, 'V', 'Barbell', '12 Min AMRAP: 3 Squat Cleans, 6 Pull-ups, 9 Squats'],
  ['Barbell Fran', 'Other Benchmark', 'F', 10, 'V', 'Barbell, Pull-up Bar', '21-15-9: Thrusters, Chest-to-Bar'],
  ['Triple Clean', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '3 Rounds: 10 HPC, 10 Power Clean, 10 Squat Clean'],
  ['Jerk & Squat', 'Other Benchmark', 'F', 12, 'V', 'Barbell', '5 Rounds: 3 Jerks, 5 Front Squats, 3 OHS'],
  ['Barbell Conditioning 1', 'Other Benchmark', 'A', 12, 'I', 'Barbell, Box', '12 Min AMRAP: 5 Deadlifts, 5 Hang Power Cleans, 5 Box Jumps'],
  ['Power Clean Ladder 10-1', 'Other Benchmark', 'F', 12, 'V', 'Barbell', '10-9-8-7-6-5-4-3-2-1: Power Cleans'],
  ['Back Squat 10x3', 'Other Benchmark', 'F', 20, 'I', 'Barbell', '10 Sets of 3 Back Squats at 75%'],
  ['Barbell Conditioning 2', 'Other Benchmark', 'A', 10, 'I', 'Barbell, Pull-up Bar', '10 Min AMRAP: 3 DL, 3 HPC, 3 FS, 3 PP, 5 Pull-ups'],
  ['Snatch Complex', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Sets: Snatch + Hang Snatch + OHS'],
  ['DL Row Complex', 'Other Benchmark', 'F', 12, 'I', 'Barbell', '5 Rounds: 5 Deadlifts, 5 Pendlay Rows, 5 Power Cleans'],
  ['Overhead Squat 5x5', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5 Sets of 5 OHS'],
  ['KB Barbell Chipper', 'Other Benchmark', 'F', 20, 'I', 'Barbell, Kettlebell', '21 KB Swings, 21 DL, 15 KB Swings, 15 Power Cleans, 9 KB Swings, 9 Thrusters'],
  ['Barbell Cycling 2', 'Other Benchmark', 'A', 10, 'V', 'Barbell', '10 Min AMRAP: 2 Squat Cleans + 2 Jerks (heavy)'],
  ['Clean & Press Ladder', 'Other Benchmark', 'F', 15, 'V', 'Barbell', '5-5-5-5-5: Clean & Press (increasing weight)'],
  ['RDL + Row', 'Other Benchmark', 'F', 12, 'I', 'Barbell', '4 Rounds: 10 RDL, 10 Bent-over Row, 10 Upright Row'],
  ['Barbell Conditioning 3', 'Other Benchmark', 'A', 15, 'I', 'Barbell, Rowing Machine', '15 Min AMRAP: 5 Hang Power Cleans, 250m Row'],
  ['Strict Press 5x5', 'Other Benchmark', 'F', 15, 'I', 'Barbell', '5 Sets of 5 Strict Press (increasing weight)'],
  ['Front Squat 8x3', 'Other Benchmark', 'F', 20, 'V', 'Barbell', '8 Sets of 3 Front Squats at 80%'],
];

// ── BLOCK F: Mixed Modal & Additional ───────────────────────────────────────
const blockF = [
  ['Row & Run 5K', 'Other Benchmark', 'F', 30, 'I', 'Rowing Machine, Bodyweight', '2500m Row + 2500m Run'],
  ['Chipper 10 Rounds', 'Other Benchmark', 'F', 25, 'I', 'Barbell, Pull-up Bar', '10 Rounds: 10 DL, 10 HPC, 10 FS, 10 PP, 10 Squats'],
  ['AMRAP 3-6-9 KB', 'Other Benchmark', 'A', 15, 'I', 'Kettlebell, Bodyweight', '15 Min AMRAP: 3-6-9 KB Swing, Burpee, Sit-up (add 3 each round)'],
  ['Ladder 1-2-3-4-5', 'Other Benchmark', 'F', 12, 'I', 'Barbell, Pull-up Bar', 'Ladder 1-5: Squat Cleans + Pull-ups'],
  ['5 Rounds Row Push', 'Other Benchmark', 'F', 15, 'I', 'Rowing Machine, Bodyweight', '5 Rounds: 500m Row, 20 Push-ups'],
  ['AMRAP Wall Ball Pull-up 12', 'Other Benchmark', 'A', 12, 'I', 'Wall Ball, Pull-up Bar', '12 Min AMRAP: 12 Wall Balls, 12 Pull-ups'],
  ['Ski Erg Chipper', 'Other Benchmark', 'F', 20, 'I', 'Ski Erg, Barbell', '2000m Ski, 30 Power Cleans, 2000m Ski'],
  ['Rowing Intervals 10x250', 'Other Benchmark', 'F', 25, 'I', 'Rowing Machine', '10x250m Row — 1min rest between'],
  ['AMRAP Row KB DL 15', 'Other Benchmark', 'A', 15, 'I', 'Rowing Machine, Kettlebell, Barbell', '15 Min AMRAP: 500m Row, 15 KB Swings, 10 Deadlifts'],
  ['Assault Bike 30 Min', 'Other Benchmark', 'F', 30, 'I', 'Assault Bike', '30 Min Assault Bike for max cals'],
  ['Death by Box Jump', 'HomeWOD', 'E', 15, 'I', 'Box', 'Min 1: 1 Box Jump, min 2: 2, continue until failure'],
  ['Death by Squat', 'HomeWOD', 'E', 15, 'B', 'Bodyweight', 'Min 1: 1 Squat, min 2: 2, continue until failure'],
  ['Death by Thruster', 'HomeWOD', 'E', 15, 'V', 'Barbell', 'Min 1: 1 Thruster, min 2: 2, continue until failure'],
  ['AMRAP HC Push Lunge 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 20 HC, 15 Push-ups, 20 Lunges'],
  ['Bodyweight Century', 'HomeWOD', 'F', 10, 'I', 'Bodyweight', '100 Reps in as few sets as possible: Push-ups or Squats'],
  ['AMRAP Burpee V Sprint 12', 'HomeWOD', 'A', 12, 'I', 'Bodyweight', '12 Min AMRAP: 6 Burpees, 12 V-ups, 100m Sprint'],
  ['Sit-up Squat 200 Reps', 'HomeWOD', 'F', 10, 'B', 'Bodyweight', '100 Sit-ups + 100 Air Squats — for time'],
  ['AMRAP Push HC Box 10', 'HomeWOD', 'A', 10, 'I', 'Box, Bodyweight', '10 Min AMRAP: 10 Push-ups, 20 HC, 10 Box Step-ups'],
  ['Bodyweight Hurricane 2', 'HomeWOD', 'F', 20, 'V', 'Bodyweight', '5 Rounds: 200m Run, 10 Burpees, 20 Squats, 20 Sit-ups'],
  ['AMRAP Jump Sit Lunge 10', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 15 Jump Squats, 15 Sit-ups, 15 Lunges'],
  ['Bodyweight Blaster', 'HomeWOD', 'F', 15, 'I', 'Bodyweight', '50 Burpees, 50 Squats, 50 Push-ups, 50 Sit-ups — for time'],
  ['AMRAP HC Pull Push 20', 'HomeWOD', 'A', 20, 'I', 'Pull-up Bar, Bodyweight', '20 Min AMRAP: 20 HC, 10 Pull-ups, 20 Push-ups'],
  ['Lunge Sprint 400', 'HomeWOD', 'F', 12, 'I', 'Bodyweight', '400m Walking Lunge + 400m Sprint'],
  ['AMRAP V Push Squat 15', 'HomeWOD', 'A', 15, 'B', 'Bodyweight', '15 Min AMRAP: 10 V-ups, 15 Push-ups, 20 Squats'],
  ['Push-up Test Max', 'HomeWOD', 'F', 5, 'B', 'Bodyweight', 'Max unbroken Push-ups'],
  ['AMRAP Mountain HC Jump 12', 'HomeWOD', 'A', 12, 'B', 'Bodyweight', '12 Min AMRAP: 20 Mountain Climbers, 20 HC, 15 Jump Squats'],
  ['Burpee Mile', 'HomeWOD', 'F', 35, 'V', 'Bodyweight', 'Every 100m: 5 Burpees — 1 Mile total'],
  ['AMRAP Pull Dip Squat 15', 'HomeWOD', 'A', 15, 'I', 'Pull-up Bar, Bodyweight', '15 Min AMRAP: 8 Pull-ups, 8 Dips, 20 Squats'],
  ['Bodyweight Open 1', 'HomeWOD', 'A', 10, 'B', 'Bodyweight', '10 Min AMRAP: 10 Burpees, 15 Squats, 20 Sit-ups'],
  ['AMRAP Push Jump Sit 8', 'HomeWOD', 'A', 8, 'B', 'Bodyweight', '8 Min AMRAP: 10 Push-ups, 10 Jump Squats, 10 Sit-ups'],
  ['KB Barbell Blend A', 'Other Benchmark', 'F', 18, 'I', 'Kettlebell, Barbell', '3 Rounds: 15 KB Swings, 12 Hang Power Cleans, 9 Push Jerks'],
  ['KB Barbell Blend B', 'Other Benchmark', 'F', 20, 'V', 'Kettlebell, Barbell, Pull-up Bar', '5 Rounds: 20 KB Swings, 15 Pull-ups, 10 Thrusters'],
  ['Row Wall Ball Chipper', 'Other Benchmark', 'F', 20, 'I', 'Rowing Machine, Wall Ball', '1000m Row, 50 Wall Balls, 1000m Row, 50 Wall Balls'],
  ['AMRAP Burpee Box Pull 12', 'Other Benchmark', 'A', 12, 'I', 'Box, Pull-up Bar', '12 Min AMRAP: 5 Burpee Box Jumps, 5 Pull-ups'],
  ['Bike Barbell Combo', 'Other Benchmark', 'F', 15, 'I', 'Assault Bike, Barbell', '5 Rounds: 15 Cal Bike, 10 Power Cleans, 10 Front Squats'],
  ['Ski KB Row Mix', 'Other Benchmark', 'A', 15, 'I', 'Ski Erg, Kettlebell, Rowing Machine', '15 Min AMRAP: 500m Ski, 20 KB Swings, 250m Row'],
  ['AMRAP Wall Ball T2B Box 15', 'Other Benchmark', 'A', 15, 'I', 'Wall Ball, Pull-up Bar, Box', '15 Min AMRAP: 15 Wall Balls, 10 T2B, 10 Box Jumps'],
  ['Row Thruster Chipper', 'Other Benchmark', 'F', 20, 'V', 'Rowing Machine, Barbell', '2000m Row, 50 Thrusters, 2000m Row'],
  ['AMRAP DL Box KB 12', 'Other Benchmark', 'A', 12, 'I', 'Barbell, Box, Kettlebell', '12 Min AMRAP: 5 Deadlifts, 10 Box Jumps, 15 KB Swings'],
  ['Triple Modal 3 Rounds', 'Other Benchmark', 'F', 20, 'I', 'Rowing Machine, Barbell, Bodyweight', '3 Rounds: 500m Row, 15 Power Cleans, 20 Burpees'],
  ['Assault Intervals 5x', 'Other Benchmark', 'F', 15, 'I', 'Assault Bike', '5x: 1 Min Max Effort / 1 Min Rest on Assault Bike'],
  ['AMRAP PC Box T2B 12', 'Other Benchmark', 'A', 12, 'V', 'Barbell, Box, Pull-up Bar', '12 Min AMRAP: 5 Power Cleans, 10 Box Jumps, 10 T2B'],
  ['Row KB AMRAP 20', 'Other Benchmark', 'A', 20, 'I', 'Rowing Machine, Kettlebell', '20 Min AMRAP: 300m Row, 20 KB Swings, 10 Burpees'],
  ['Bike Run KB', 'Other Benchmark', 'F', 20, 'I', 'Assault Bike, Kettlebell', '4 Rounds: 10 Cal Bike, 400m Run, 20 KB Swings'],
  ['AMRAP WB DL Box 15', 'Other Benchmark', 'A', 15, 'I', 'Wall Ball, Barbell, Box', '15 Min AMRAP: 15 Wall Balls, 10 Deadlifts, 10 Box Jumps'],
  ['Snatch + Row', 'Other Benchmark', 'F', 15, 'V', 'Barbell, Rowing Machine', '5 Rounds: 5 Squat Snatches, 250m Row'],
  ['KB Swing 10x10', 'Other Benchmark', 'F', 10, 'I', 'Kettlebell', '10 Sets of 10 KB Swings (EMOM style)'],
  ['Pull-up 10x10', 'Other Benchmark', 'F', 12, 'I', 'Pull-up Bar', '10 Sets of 10 Pull-ups (every 90s)'],
  ['AMRAP Burpee Thruster 10', 'Other Benchmark', 'A', 10, 'V', 'Barbell', '10 Min AMRAP: 5 Thrusters, 10 Burpees'],
  ['Row Deadlift 5 Rounds', 'Other Benchmark', 'F', 18, 'I', 'Rowing Machine, Barbell', '5 Rounds: 500m Row, 10 Deadlifts'],
  ['AMRAP C2B KB Box 15', 'Other Benchmark', 'A', 15, 'V', 'Pull-up Bar, Kettlebell, Box', '15 Min AMRAP: 5 C2B, 10 KB Swings, 10 Box Jumps'],
  ['Ski Pull-up Chipper', 'Other Benchmark', 'F', 15, 'V', 'Ski Erg, Pull-up Bar', '100 Cal Ski, 50 Pull-ups, 50 Cal Ski, 25 Pull-ups'],
  ['AMRAP WB PC DU 12', 'Other Benchmark', 'A', 12, 'I', 'Wall Ball, Barbell, Jump Rope', '12 Min AMRAP: 15 WB, 10 PC, 30 DU'],
  ['Barbell Bias WOD 1', 'Other Benchmark', 'F', 20, 'V', 'Barbell, Pull-up Bar', '10 Rounds: 3 Squat Cleans, 3 Jerks, 5 Bar Muscle-ups'],
  ['Barbell Bias WOD 2', 'Other Benchmark', 'F', 18, 'I', 'Barbell, Bodyweight', '5 Rounds: 10 Deadlifts, 10 HPC, 10 FS, 10 PP, 10 Burpees'],
  ['AMRAP DL T2B Burpee 15', 'Other Benchmark', 'A', 15, 'I', 'Barbell, Pull-up Bar', '15 Min AMRAP: 5 Deadlifts, 10 T2B, 5 Burpees'],
  ['Row Bike Run Tri', 'Other Benchmark', 'F', 30, 'I', 'Rowing Machine, Assault Bike', '1000m Row, 20 Cal Bike, 800m Run — 3 Rounds'],
  ['KB Swing 500', 'Other Benchmark', 'F', 25, 'I', 'Kettlebell', '500 KB Swings for time — partition as needed'],
  ['AMRAP HSPU PC Box 10', 'Other Benchmark', 'A', 10, 'V', 'Barbell, Box, Bodyweight', '10 Min AMRAP: 5 HSPU, 5 Power Cleans, 10 Box Jumps'],
  ['Run KB Barbell 3x', 'Other Benchmark', 'F', 20, 'I', 'Kettlebell, Barbell', '3 Rounds: 800m Run, 20 KB Swings, 10 Hang Power Cleans'],
  ['AMRAP C2B WB DL 15', 'Other Benchmark', 'A', 15, 'V', 'Pull-up Bar, Wall Ball, Barbell', '15 Min AMRAP: 5 C2B Pull-ups, 15 Wall Balls, 5 Deadlifts'],
  ['Box Jump Barbell 5 Rounds', 'Other Benchmark', 'F', 18, 'I', 'Box, Barbell', '5 Rounds: 15 Box Jumps, 10 Power Cleans, 5 Push Jerks'],
  ['Bike KB Pull Chipper', 'Other Benchmark', 'F', 20, 'I', 'Assault Bike, Kettlebell, Pull-up Bar', '50 Cal Bike, 50 KB Swings, 50 Pull-ups, 50 Cal Bike'],
  ['AMRAP Row PC Burpee 12', 'Other Benchmark', 'A', 12, 'I', 'Rowing Machine, Barbell', '12 Min AMRAP: 250m Row, 5 Power Cleans, 5 Burpees'],
  ['KB Barbell Full Chipper', 'Other Benchmark', 'F', 25, 'V', 'Kettlebell, Barbell, Pull-up Bar', '30 KB Swings, 20 Pull-ups, 30 Thrusters, 20 Pull-ups, 30 KB Swings'],
  ['AMRAP WB Box KB 20', 'Other Benchmark', 'A', 20, 'I', 'Wall Ball, Box, Kettlebell', '20 Min AMRAP: 20 Wall Balls, 15 Box Jumps, 15 KB Swings'],
  ['Endurance Chipper', 'Other Benchmark', 'F', 40, 'V', 'Rowing Machine, Barbell, Bodyweight', '2000m Row, 50 Thrusters, 30 Pull-ups, 30 Burpees, 2000m Row'],
  ['AMRAP DL Pull Box 12', 'Other Benchmark', 'A', 12, 'I', 'Barbell, Pull-up Bar, Box', '12 Min AMRAP: 5 Deadlifts, 10 Pull-ups, 15 Box Jumps'],
];

// ── MAIN ─────────────────────────────────────────────────────────────────────
const existing = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
const existingNames = new Set(existing.map(w => w.name.toLowerCase().trim()));

let nextId = Math.max(...existing.map(w => parseInt(w.id)).filter(n => !isNaN(n))) + 1;
const newWods = [];

for (const compact of [...blockA, ...blockB, ...blockC, ...blockD, ...blockE, ...blockF]) {
  const name = compact[0];
  if (existingNames.has(name.toLowerCase().trim())) {
    console.log(`SKIP (duplicate): ${name}`);
    continue;
  }
  newWods.push(build(nextId++, compact));
  existingNames.add(name.toLowerCase().trim());
}

const merged = [...existing, ...newWods];
fs.writeFileSync(DATA_FILE, JSON.stringify(merged, null, 2), 'utf8');
console.log(`\nDone! Added ${newWods.length} new WODs.`);
console.log(`Total: ${merged.length} WODs`);
console.log(`IDs: ${existing.length + 1} – ${nextId - 1}`);
