-- Migration 021: Neue WOD-Kategorien (183 WODs)
-- HIIT · Kraft-Ausdauer · Kraft-Wenig-Zeit · Krafttraining
-- Stand: Mai 2026

INSERT INTO wods (name, type, estimated_minutes, equipment_tags, description, wod_category, is_visible)
VALUES
  ('Inferno', 'tabata', 8, '{bodyweight}', '8 Runden 20s/10s: Burpees / Mountain Climbers', 'hiit', true),
  ('Boden-Battle', 'amrap', 10, '{bodyweight}', '10 Push-ups · 15 Sit-ups · 20 Squats', 'hiit', true),
  ('Feuer-Intervall', 'timer', 9, '{bodyweight}', '6 Runden: 30s Sprinter Steps + 30s Jumping Jacks / 30s Pause', 'hiit', true),
  ('Dirty 30', 'fortime', 12, '{bodyweight}', '30 Burpees · 30 Push-ups · 30 Air Squats', 'hiit', true),
  ('Cardio-Kreis', 'emom', 10, '{bodyweight}', 'Odd: 15 High Knees + 10 Squats · Even: 10 Push-ups + 15 Sit-ups', 'hiit', true),
  ('Bär und Berg', 'amrap', 12, '{bodyweight}', '8 Bear Crawl Steps · 12 Mountain Climbers · 10 Plank Shoulder Taps', 'hiit', true),
  ('Sprint-Matrix', 'tabata', 12, '{bodyweight}', '3 Übungen je 8 Runden: Squat Jumps / Burpees / V-Ups', 'hiit', true),
  ('Schnelle 15', 'amrap', 15, '{bodyweight}', '5 Burpees · 10 Push-ups · 15 Squats · 20 High Knees', 'hiit', true),
  ('Push-Sit', 'emom', 10, '{bodyweight}', 'Odd: 15 Push-ups · Even: 20 Sit-ups', 'hiit', true),
  ('Core-Bomb', 'tabata', 8, '{bodyweight}', '8 Runden 20s/10s: V-Ups / Hollow Rocks', 'hiit', true),
  ('Vierzig-Sekunden', 'timer', 12, '{bodyweight}', '6 Runden: 40s Burpees / 20s Pause / 40s Squats / 20s Pause', 'hiit', true),
  ('Elbow Grease', 'amrap', 10, '{bodyweight}', '10 Pike Push-ups · 12 Tricep Dips · 15 Plank Shoulder Taps', 'hiit', true),
  ('Leg Day Express', 'emom', 12, '{bodyweight}', 'Odd: 20 Air Squats · Even: 16 Reverse Lunges (8/Seite)', 'hiit', true),
  ('Full Send', 'fortime', 10, '{bodyweight}', '5 Runden: 10 Burpees · 15 Sit-ups · 20 Squats', 'hiit', true),
  ('Plank-Kette', 'emom', 8, '{bodyweight}', 'Jede Minute: 30s Plank + 10 Mountain Climbers', 'hiit', true),
  ('Upper Express', 'tabata', 8, '{bodyweight}', '8 Runden: Push-up Varianten (wide / narrow / pike)', 'hiit', true),
  ('Double Down', 'amrap', 15, '{bodyweight}', '12 Push-ups · 12 Sit-ups · 12 Squats · 12 Glute Bridges', 'hiit', true),
  ('Step-Burn', 'timer', 10, '{bodyweight}', '5 Runden: 45s Step-ups (Stuhl/Treppe) / 15s Pause', 'hiit', true),
  ('Nacht-Sprint', 'emom', 10, '{bodyweight}', 'Odd: 12 Burpees · Even: 20 Hollow Rocks', 'hiit', true),
  ('Tri-Set', 'fortime', 12, '{bodyweight}', '4 Runden: 15 Push-ups · 20 Squats · 25 Sit-ups', 'hiit', true),
  ('Inchworm-Flow', 'amrap', 10, '{bodyweight}', '5 Inchworms · 10 Push-ups · 15 Squats', 'hiit', true),
  ('Tabata Total', 'tabata', 16, '{bodyweight}', '4 Übungen je 8 Runden: Squats / Push-ups / Sit-ups / Burpees', 'hiit', true),
  ('Lunge & Burn', 'emom', 12, '{bodyweight}', 'Odd: 20 Reverse Lunges · Even: 15 Push-ups', 'hiit', true),
  ('Core-Uhr', 'fortime', 10, '{bodyweight}', '50-40-30-20-10: Sit-ups · Squats (alternierend)', 'hiit', true),
  ('Bear Komplex', 'amrap', 10, '{bodyweight}', '10 Bear Crawl Steps · 10 Glute Bridges · 10 Superman', 'hiit', true),
  ('Hip-Burn', 'tabata', 8, '{bodyweight}', '8 Runden: Glute Bridge Pulse / Hip Thrust Hold', 'hiit', true),
  ('12-Takt', 'emom', 12, '{bodyweight}', 'Jede Minute: 8 Burpees (Pace halten)', 'hiit', true),
  ('Schulterbrenner', 'amrap', 10, '{bodyweight}', '12 Pike Push-ups · 15 Plank Shoulder Taps · 10 Superman', 'hiit', true),
  ('Springseil-Ersatz', 'timer', 9, '{bodyweight}', '6 Runden: 30s Jumping Jacks + 30s High Knees / 30s Pause', 'hiit', true),
  ('Last Man Standing', 'fortime', 15, '{bodyweight}', '21-15-9: Air Squats · Push-ups · Burpees', 'hiit', true),
  ('Eltern-Nacht', 'amrap', 8, '{bodyweight}', '10 Bear Crawl Steps · 15 Prisoner Squats · 10 Pike Push-ups', 'hiit', true),
  ('Core-Burn', 'amrap', 10, '{bodyweight}', '12 V-Ups · 10 Hollow Rocks · 8 Arch Rocks', 'hiit', true),
  ('Silent Grind', 'amrap', 12, '{bodyweight}', '20 Glute Bridges · 15 Slow Squats · 10 Push-ups', 'hiit', true),
  ('Fundament', 'emom', 10, '{bodyweight}', 'Odd: 10 Slow Squats + 10 Glute Bridges · Even: 10 Push-ups + 20s Plank', 'hiit', true),
  ('Rücken-Stark', 'amrap', 10, '{bodyweight}', '12 Superman · 10 Bird Dog (5/Seite) · 15 Glute Bridges', 'hiit', true),
  ('Nacht-Flow', 'emom', 12, '{bodyweight}', 'Odd: 12 Reverse Lunges · Even: 12 Pike Push-ups + 15s Plank', 'hiit', true),
  ('Kniefreundlich', 'amrap', 10, '{bodyweight}', '15 Wall Sit-Pulse · 12 Glute Bridges · 10 Side-lying Leg Raises', 'hiit', true),
  ('Stille Kraft', 'amrap', 15, '{bodyweight}', '10 Bear Crawl Steps · 10 Push-ups · 10 Sit-ups · 20 Glute Bridges', 'hiit', true),
  ('Schulter-Ausdauer', 'emom', 10, '{bodyweight}', 'Odd: 12 Pike Push-ups · Even: 20s Plank + 10 Shoulder Taps', 'hiit', true),
  ('Beine ohne Geräusch', 'amrap', 10, '{bodyweight}', '15 Prisoner Squats · 10 Reverse Lunges · 15 Glute Bridges', 'hiit', true),
  ('Morgen-Routine', 'emom', 8, '{bodyweight}', 'Jede Minute: 8 Push-ups + 12 Sit-ups + 8 Squats', 'hiit', true),
  ('Kern und Kraft', 'amrap', 12, '{bodyweight}', '10 V-Ups · 10 Push-ups · 15 Squats · 10 Superman', 'hiit', true),
  ('Hip & Core', 'emom', 10, '{bodyweight}', 'Odd: 20 Hip Thrusts · Even: 15 Dead Bugs', 'hiit', true),
  ('Ganzkörper-Leise', 'amrap', 12, '{bodyweight}', '8 Inchworms · 10 Push-ups · 12 Squats · 15 Glute Bridges', 'hiit', true),
  ('Trizeps-Abend', 'amrap', 10, '{bodyweight}', '12 Tricep Dips · 10 Pike Push-ups · 15 Plank Shoulder Taps', 'hiit', true),
  ('Rücken-Kette', 'emom', 10, '{bodyweight}', 'Odd: 12 Superman + 10 Bird Dog · Even: 15 Glute Bridges + 20s Plank', 'hiit', true),
  ('Niedriges Tempo', 'amrap', 15, '{bodyweight}', '10 Slow Push-ups (3s runter) · 15 Slow Squats (3s runter) · 12 Glute Bridges', 'hiit', true),
  ('Bauch-Fokus', 'emom', 10, '{bodyweight}', 'Odd: 15 Sit-ups + 10 V-Ups · Even: 20s Hollow Hold + 10 Leg Raises', 'hiit', true),
  ('Push-Pause', 'amrap', 10, '{bodyweight}', '10 Push-ups · 30s Plank · 15 Squats · 30s Wall Sit', 'hiit', true),
  ('Abend-Reset', 'emom', 12, '{bodyweight}', 'Odd: 10 Bear Crawl Steps · Even: 10 Superman + 10 Bird Dog', 'hiit', true),
  ('Quadrizeps-Feuer', 'amrap', 10, '{bodyweight}', '20 Prisoner Squats · 15 Reverse Lunges · 30s Wall Sit', 'hiit', true),
  ('Schulter-Flow', 'emom', 8, '{bodyweight}', 'Jede Minute: 10 Pike Push-ups + 15 Plank Shoulder Taps', 'hiit', true),
  ('Sanfte Intensität', 'amrap', 12, '{bodyweight}', '10 Slow Burpees (ohne Sprung) · 15 Squats · 12 Push-ups', 'hiit', true),
  ('Core-Ausdauer', 'emom', 10, '{bodyweight}', 'Odd: 15 Dead Bugs · Even: 20s Hollow Hold + 10 Leg Raises', 'hiit', true),
  ('Push & Hinge', 'amrap', 10, '{bodyweight}', '12 Push-ups · 15 Good Mornings (Bodyweight) · 10 Superman', 'hiit', true),
  ('Spät-Abend', 'amrap', 8, '{bodyweight}', '8 Inchworms · 12 Push-ups · 16 Glute Bridges', 'hiit', true),
  ('Ganzkörper-15', 'emom', 15, '{bodyweight}', 'Min 1: 12 Squats · Min 2: 10 Push-ups · Min 3: 15 Sit-ups', 'hiit', true),
  ('Hüft-Kraft', 'amrap', 10, '{bodyweight}', '20 Hip Thrusts · 15 Clamshells (7/Seite) · 12 Glute Bridges', 'hiit', true),
  ('Ruhig-Stark', 'amrap', 12, '{bodyweight}', '10 Bear Crawl Steps · 10 Pike Push-ups · 15 Glute Bridges · 10 V-Ups', 'hiit', true),
  ('Letzter Satz', 'emom', 10, '{bodyweight}', 'Odd: 15 Prisoner Squats + 10 Glute Bridges · Even: 12 Push-ups + 20s Plank', 'hiit', true),
  ('Eltern-Abend', 'amrap', 10, '{dumbbell}', '10 Kurzhantel Goblet Squat (leicht) · 10 Push-ups · 12 Kurzhantel Row', 'kraft_ausdauer', true),
  ('Leichtes Eisen', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Deadlift · Even: 10 Push-ups + 10 Sit-ups', 'kraft_ausdauer', true),
  ('Kettlebell-Flow', 'amrap', 12, '{kettlebell}', '8 Kettlebell Swing · 10 Push-ups · 12 Goblet Squat', 'kraft_ausdauer', true),
  ('Ganzkörper-Leicht', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Thruster · Even: 10 Push-ups + 15 Glute Bridges', 'kraft_ausdauer', true),
  ('Rücken & Körper', 'amrap', 10, '{dumbbell}', '10 Kurzhantel Row · 10 Squats · 10 Superman · 10 Push-ups', 'kraft_ausdauer', true),
  ('Hüft-Zirkel', 'emom', 12, '{kettlebell}', 'Odd: 10 Kettlebell Swing · Even: 12 Glute Bridges + 10 Reverse Lunges', 'kraft_ausdauer', true),
  ('Kurzhantel-Ausdauer', 'amrap', 12, '{dumbbell}', '8 Kurzhantel Hang Clean · 10 Kurzhantel Squat · 8 Kurzhantel Press · 10 Sit-ups', 'kraft_ausdauer', true),
  ('Koordination', 'amrap', 10, '{kettlebell}', '6 Kettlebell Clean (3/Seite) · 10 Push-ups · 12 Air Squats', 'kraft_ausdauer', true),
  ('Schulter-Kreis', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Press + 10 Lateral Raise · Even: 12 Pike Push-ups', 'kraft_ausdauer', true),
  ('Beine & KB', 'amrap', 12, '{kettlebell}', '10 Goblet Squat · 10 Kettlebell Swing · 12 Reverse Lunges', 'kraft_ausdauer', true),
  ('Push-Pull-Leicht', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Row · Even: 10 Kurzhantel Press + 8 Lateral Raise', 'kraft_ausdauer', true),
  ('Nacht-Zirkel', 'amrap', 10, '{dumbbell}', '8 Kurzhantel Deadlift · 10 Push-ups · 10 Kurzhantel Curl · 15 Glute Bridges', 'kraft_ausdauer', true),
  ('Kettlebell-Cardio', 'amrap', 12, '{kettlebell}', '12 Kettlebell Swing · 8 Push-ups · 10 Goblet Squat · 10 Sit-ups', 'kraft_ausdauer', true),
  ('Kurzhantel-Kreis', 'emom', 12, '{dumbbell}', 'Odd: 8 Kurzhantel Squat + 8 Kurzhantel Row · Even: 8 Kurzhantel Press + 10 Sit-ups', 'kraft_ausdauer', true),
  ('Functional Flow', 'amrap', 10, '{kettlebell}', '8 Kettlebell Swing · 8 Push-ups · 8 Goblet Squat · 8 Superman', 'kraft_ausdauer', true),
  ('Leichte Last', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Romanian Deadlift · Even: 12 Push-ups + 12 Glute Bridges', 'kraft_ausdauer', true),
  ('Arm & Körper', 'amrap', 10, '{dumbbell}', '10 Kurzhantel Curl · 10 Tricep Extension · 10 Kurzhantel Row · 10 Squats', 'kraft_ausdauer', true),
  ('Koordinativ', 'amrap', 12, '{kettlebell}', '5 Kettlebell Clean & Press (5/Seite) · 10 Push-ups · 12 Air Squats', 'kraft_ausdauer', true),
  ('Kurzhantel-Tempo', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Hang Clean · Even: 8 Kurzhantel Press + 10 Lateral Raise', 'kraft_ausdauer', true),
  ('Hybrid-Ausdauer', 'amrap', 15, '{dumbbell}', '8 Kurzhantel Deadlift · 10 Push-ups · 10 Kurzhantel Row · 15 Squats', 'kraft_ausdauer', true),
  ('Oberkörper-Mix', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Row + 8 Kurzhantel Curl · Even: 10 Pike Push-ups + 10 Tricep Dips', 'kraft_ausdauer', true),
  ('Bein-Eisen', 'amrap', 12, '{kettlebell}', '10 Goblet Squat · 10 Kettlebell Deadlift · 12 Reverse Lunges · 15 Glute Bridges', 'kraft_ausdauer', true),
  ('Kurzhantel-Core', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Deadlift · Even: 10 V-Ups + 20s Kurzhantel Plank Hold', 'kraft_ausdauer', true),
  ('Ganzkörper-KB', 'amrap', 12, '{kettlebell}', '8 Kettlebell Swing · 6 Kettlebell Goblet Squat · 8 Push-ups · 10 Sit-ups', 'kraft_ausdauer', true),
  ('Leise & Effektiv', 'emom', 12, '{dumbbell}', 'Odd: 8 Kurzhantel Romanian Deadlift · Even: 8 Kurzhantel Press + 10 Glute Bridges', 'kraft_ausdauer', true),
  ('Kurzhantel-Zirkel', 'amrap', 10, '{dumbbell}', '8 Kurzhantel Thruster · 10 Kurzhantel Row · 10 Kurzhantel Curl · 10 Kurzhantel Lateral Raise', 'kraft_ausdauer', true),
  ('Kettlebell-Hybrid', 'amrap', 10, '{kettlebell}', '10 Kettlebell Swing · 10 Push-ups · 8 Goblet Squat · 10 Superman', 'kraft_ausdauer', true),
  ('Abend-Eisen', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Squat + 8 Kurzhantel Row · Even: 10 Push-ups + 10 V-Ups', 'kraft_ausdauer', true),
  ('Kontrolliert', 'amrap', 12, '{kettlebell}', '8 Kettlebell Clean (4/Seite) · 10 Squats · 8 Push-ups · 10 Glute Bridges', 'kraft_ausdauer', true),
  ('Full-Body-Leicht', 'emom', 15, '{dumbbell}', 'Min 1: 8 Kurzhantel Deadlift · Min 2: 10 Push-ups · Min 3: 8 Kurzhantel Row + 10 Squats', 'kraft_ausdauer', true),
  ('Kurzhantel-Morgen', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Press + 10 Lateral Raise · Even: 12 Squats + 10 Push-ups', 'kraft_ausdauer', true),
  ('Kettlebell-Zirkel II', 'amrap', 12, '{kettlebell}', '10 Kettlebell Swing · 8 Goblet Squat · 10 Push-ups · 12 Glute Bridges', 'kraft_ausdauer', true),
  ('Kurzhantel-Kette', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Row + 8 Kurzhantel Curl · Even: 8 Kurzhantel Thruster', 'kraft_ausdauer', true),
  ('Leichte Last II', 'amrap', 10, '{dumbbell}', '10 Kurzhantel Deadlift · 10 Push-ups · 10 Kurzhantel Curl · 15 Squats', 'kraft_ausdauer', true),
  ('Kettlebell-Körper', 'amrap', 12, '{kettlebell}', '8 Kettlebell Swing · 6 Kettlebell Goblet Squat · 10 Push-ups · 10 V-Ups', 'kraft_ausdauer', true),
  ('Kurzhantel-Ausdauer II', 'emom', 12, '{dumbbell}', 'Odd: 8 Kurzhantel Squat + 8 Kurzhantel Row · Even: 10 Push-ups + 15 Glute Bridges', 'kraft_ausdauer', true),
  ('Mix & Move', 'amrap', 10, '{kettlebell}', '10 Kettlebell Swing · 10 Push-ups · 10 Sit-ups · 10 Goblet Squat', 'kraft_ausdauer', true),
  ('Kurzhantel-Press-Kreis', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Arnold Press · Even: 12 Pike Push-ups + 10 Squats', 'kraft_ausdauer', true),
  ('Hüft & Zug', 'amrap', 12, '{kettlebell}', '12 Kettlebell Swing · 10 Glute Bridges · 8 Superman · 10 Push-ups', 'kraft_ausdauer', true),
  ('Kurzhantel-Trio', 'emom', 12, '{dumbbell}', 'Odd: 8 Kurzhantel Deadlift · Even: 8 Kurzhantel Press + 8 Lateral Raise', 'kraft_ausdauer', true),
  ('Kettlebell-Ganzkörper', 'amrap', 10, '{kettlebell}', '6 Kettlebell Clean (3/Seite) · 8 Goblet Squat · 10 Push-ups · 12 Sit-ups', 'kraft_ausdauer', true),
  ('Kurzhantel-Rhythmus', 'emom', 10, '{dumbbell}', 'Odd: 10 Kurzhantel Thruster · Even: 10 V-Ups + 10 Glute Bridges', 'kraft_ausdauer', true),
  ('Zug & Core', 'amrap', 12, '{dumbbell}', '10 Kurzhantel Row · 10 Superman · 12 Glute Bridges · 10 Push-ups', 'kraft_ausdauer', true),
  ('Kettlebell-Compound', 'amrap', 12, '{kettlebell}', '8 Kettlebell Swing · 6 Kettlebell Goblet Squat · 8 Push-ups · 10 Reverse Lunges', 'kraft_ausdauer', true),
  ('Kurzhantel-Schulter-Mix', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Press + 10 Lateral Raise · Even: 10 Pike Push-ups + 15 Squats', 'kraft_ausdauer', true),
  ('Leiser Zirkel', 'amrap', 12, '{dumbbell}', '8 Kurzhantel Romanian Deadlift · 10 Push-ups · 8 Kurzhantel Row · 15 Glute Bridges', 'kraft_ausdauer', true),
  ('Kettlebell-Ausdauer II', 'emom', 12, '{kettlebell}', 'Odd: 10 Kettlebell Swing + 5 Goblet Squat · Even: 10 Push-ups + 10 Sit-ups', 'kraft_ausdauer', true),
  ('Kurzhantel-Flow II', 'amrap', 10, '{dumbbell}', '8 Kurzhantel Hang Clean · 8 Kurzhantel Squat · 8 Kurzhantel Press · 8 Kurzhantel Row', 'kraft_ausdauer', true),
  ('Koordinativ II', 'emom', 10, '{kettlebell}', 'Odd: 6 Kettlebell Clean & Press (3/Seite) · Even: 12 Air Squats + 10 Push-ups', 'kraft_ausdauer', true),
  ('Abschluss-Zirkel', 'amrap', 15, '{dumbbell}', '8 Kurzhantel Deadlift · 10 Push-ups · 8 Kurzhantel Row · 10 Squats · 10 Glute Bridges', 'kraft_ausdauer', true),
  ('KB Density', 'emom', 10, '{kettlebell}', 'Odd: 10 Kettlebell Swings · Even: 5 Goblet Squats', 'kraft_wenig_zeit', true),
  ('DB Komplex', 'amrap', 8, '{dumbbell}', '8 Kurzhantel Hang Clean · 8 Kurzhantel Press · 8 Kurzhantel Row', 'kraft_wenig_zeit', true),
  ('Kettlebell-Feuer', 'fortime', 10, '{kettlebell}', '3 Runden: 15 Kettlebell Swings · 10 Goblet Squats · 5 Kettlebell Press', 'kraft_wenig_zeit', true),
  ('Dumbbell-Dichte', 'emom', 12, '{dumbbell}', 'Odd: 10 Kurzhantel Deadlift · Even: 8 Kurzhantel Row (4/Seite)', 'kraft_wenig_zeit', true),
  ('Schwing-Kreis', 'amrap', 10, '{kettlebell}', '15 Kettlebell Swings · 10 Push-ups · 12 Goblet Squats', 'kraft_wenig_zeit', true),
  ('DB Schulter', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Press · Even: 10 Lateral Raises + 10 Front Raises', 'kraft_wenig_zeit', true),
  ('KB Komplex', 'fortime', 12, '{kettlebell}', '4 Runden: 10 Kettlebell Clean · 10 Kettlebell Squat · 10 Kettlebell Swing', 'kraft_wenig_zeit', true),
  ('Dumbbell-Paare', 'amrap', 12, '{dumbbell}', '8 Kurzhantel Thruster · 10 Kurzhantel Row · 12 Kurzhantel Deadlift', 'kraft_wenig_zeit', true),
  ('Kettlebell-Griff', 'emom', 10, '{kettlebell}', 'Odd: 6 Kettlebell Snatch (3/Seite) · Even: 10 Kettlebell Swing + 5 Goblet Squat', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Ladder', 'fortime', 10, '{dumbbell}', '5-10-15: Kurzhantel Deadlift · Kurzhantel Row · Kurzhantel Curl', 'kraft_wenig_zeit', true),
  ('Eisen-Runden', 'amrap', 10, '{dumbbell,kettlebell}', '10 Kettlebell Swings · 8 Kurzhantel Press · 10 Goblet Squats', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Hinge', 'emom', 12, '{dumbbell}', 'Odd: 10 Kurzhantel Romanian Deadlift · Even: 10 Kurzhantel Row (5/Seite)', 'kraft_wenig_zeit', true),
  ('Kettlebell-Endurance', 'amrap', 15, '{kettlebell}', '12 Kettlebell Swings · 8 Goblet Squats · 6 Kettlebell Press', 'kraft_wenig_zeit', true),
  ('Dumbbell-Brenner', 'fortime', 10, '{dumbbell}', '3 Runden: 10 Kurzhantel Thruster · 12 Kurzhantel Row · 15 Kurzhantel Deadlift', 'kraft_wenig_zeit', true),
  ('Einarm-KB', 'emom', 10, '{kettlebell}', 'Odd: 6 Kettlebell Clean & Press links · Even: 6 Kettlebell Clean & Press rechts', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Push-Pull', 'amrap', 12, '{dumbbell}', '10 Kurzhantel Press · 10 Kurzhantel Row · 10 Kurzhantel Curl · 10 Lateral Raise', 'kraft_wenig_zeit', true),
  ('Farmer-Flow', 'fortime', 8, '{dumbbell}', '3 Runden: 20 Schritte Farmer Carry · 10 Kurzhantel Squat · 10 Kurzhantel Row', 'kraft_wenig_zeit', true),
  ('Kettlebell-Zirkel', 'amrap', 10, '{kettlebell}', '8 Kettlebell Deadlift · 8 Kettlebell Swing · 8 Goblet Squat', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Schnell', 'emom', 8, '{dumbbell}', 'Jede Minute: 8 Kurzhantel Hang Clean + 8 Kurzhantel Press', 'kraft_wenig_zeit', true),
  ('Pendel', 'fortime', 12, '{kettlebell}', '21-15-9: Kettlebell Swings · Goblet Squats', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Oberkörper', 'amrap', 10, '{dumbbell}', '10 Kurzhantel Bench Press (Boden) · 10 Kurzhantel Row · 10 Kurzhantel Curl · 8 Tricep Extension', 'kraft_wenig_zeit', true),
  ('Kettlebell-Sprint', 'tabata', 8, '{kettlebell}', '8 Runden: 20s Kettlebell Swings / 10s Pause', 'kraft_wenig_zeit', true),
  ('Dichte-15', 'emom', 15, '{dumbbell}', 'Odd: 8 Kurzhantel Deadlift · Even: 8 Kurzhantel Row · Min 3: 8 Kurzhantel Press', 'kraft_wenig_zeit', true),
  ('Kettlebell-Flow II', 'amrap', 12, '{kettlebell}', '6 Kettlebell Snatch (3/Seite) · 8 Goblet Squat · 10 Kettlebell Swing', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Wechsel', 'fortime', 10, '{dumbbell}', '4 Runden: 8 Kurzhantel Thruster · 8 Kurzhantel Reverse Lunge · 8 Kurzhantel Row', 'kraft_wenig_zeit', true),
  ('Einbein-KB', 'emom', 10, '{kettlebell}', 'Odd: 6 Kettlebell Single-leg Deadlift links · Even: 6 Kettlebell Single-leg Deadlift rechts', 'kraft_wenig_zeit', true),
  ('Kurzhantel-Volumen', 'amrap', 15, '{dumbbell}', '10 Kurzhantel Deadlift · 10 Kurzhantel Row · 10 Kurzhantel Press · 10 Kurzhantel Curl', 'kraft_wenig_zeit', true),
  ('Kettlebell-Dichte', 'fortime', 8, '{kettlebell}', '100 Kettlebell Swings (in möglichst wenig Sätzen)', 'kraft_wenig_zeit', true),
  ('Schulter-Eisen', 'emom', 10, '{dumbbell}', 'Odd: 8 Kurzhantel Arnold Press · Even: 10 Lateral Raise + 10 Front Raise', 'kraft_wenig_zeit', true),
  ('Total-DB', 'amrap', 12, '{dumbbell}', '8 Kurzhantel Clean · 8 Kurzhantel Squat · 8 Kurzhantel Press · 8 Kurzhantel Row', 'kraft_wenig_zeit', true),
  ('Ganzkörper A', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Bench Press (Langhantel oder Kurzhantel) · 3. Kurzhantel Row · 4. Kurzhantel Overhead Press · 5. Kurzhantel Curl · Core: Plank 3×45s — 4×8 / 4×8 / 4×10 / 3×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper B', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel) · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Kurzhantel Squat · 5. Tricep Extension · Core: Dead Bug 3×10 — 4×6 / 4×8 / 4×10 / 3×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Push/Pull A', 'krafttraining', 35, '{dumbbell}', 'Oberkörper: 1. Kurzhantel Bench Press · 2. Kurzhantel Row · 3. Kurzhantel Overhead Press · 4. Kurzhantel Curl · 5. Tricep Extension · Core: V-Ups 3×15 — 4×8 / 4×10 / 3×10 / 3×12 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Unterkörper A', 'krafttraining', 35, '{barbell,dumbbell}', 'Unterkörper + Core: 1. Squat (Langhantel oder Goblet) · 2. Romanian Deadlift · 3. Reverse Lunge · 4. Hip Thrust · 5. Calf Raise · Core: Hollow Rocks 3×15 — 4×8 / 4×10 / 3×12 / 3×15 / 4×20 · Pause: 90s', 'krafttraining', true),
  ('5×5 Ganzkörper A', 'krafttraining', 35, '{barbell,dumbbell}', 'Maximalkraft: 1. Squat (Langhantel oder Goblet, schwer) · 2. Deadlift (Langhantel oder Kurzhantel, schwer) · 3. Kurzhantel Row (schwer) · 4. Kurzhantel Bench Press (schwer) — 5×5 je Übung · Pause: 2–3 Min', 'krafttraining', true),
  ('Oberkörper A', 'krafttraining', 35, '{dumbbell}', 'Oberkörper + Core: 1. Kurzhantel Bench Press · 2. Kurzhantel Row · 3. Kurzhantel Overhead Press · 4. Lateral Raise · 5. Kurzhantel Curl · Core: Plank + Side Plank 3×40s — 4×8 / 4×10 / 3×10 / 3×15 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper C', 'krafttraining', 35, '{dumbbell,kettlebell}', 'Ganzkörper: 1. Kettlebell Goblet Squat · 2. Kettlebell Deadlift · 3. Kurzhantel Row · 4. Kurzhantel Press · 5. Kurzhantel Curl · Core: Bird Dog 3×10 — 4×10 / 4×10 / 4×10 / 3×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Push/Pull B', 'krafttraining', 35, '{barbell,dumbbell}', 'Oberkörper: 1. Langhantel oder Kurzhantel Bench Press · 2. Kurzhantel Row · 3. Kurzhantel Fly · 4. Kurzhantel Reverse Fly · 5. Tricep Dips · Core: Hollow Hold 3×30s — 4×8 / 4×10 / 3×12 / 3×12 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper D', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel) · 2. Kurzhantel Bench Press · 3. Kurzhantel Squat · 4. Kurzhantel Overhead Press · 5. Kurzhantel Curl · 6. Tricep Extension — 4×6 / 3×8 / 3×10 / 3×10 / 3×12 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper L', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Kurzhantel Overhead Press · 5. Hip Thrust · Core: Plank 3×45s — 4×10 / 4×8 / 4×10 / 3×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper M', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel) · 2. Kurzhantel Incline Press · 3. Kurzhantel Row · 4. Goblet Squat · 5. Lateral Raise · Core: V-Ups 3×15 — 4×8 / 4×8 / 4×10 / 3×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper E', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Romanian Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Lateral Raise · Core: V-Ups 3×15 — 4×8 / 4×10 / 4×8 / 4×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Push/Pull C', 'krafttraining', 35, '{dumbbell}', 'Oberkörper: 1. Kurzhantel Overhead Press · 2. Kurzhantel Row · 3. Arnold Press · 4. Kurzhantel Curl · 5. Tricep Extension · Core: Dead Bug 3×10 — 4×8 / 4×10 / 3×10 / 3×12 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper F', 'krafttraining', 35, '{barbell,dumbbell,kettlebell}', 'Ganzkörper: 1. Squat (Langhantel oder Kettlebell) · 2. Kurzhantel Row · 3. Kurzhantel Press · 4. Hip Thrust · 5. Kurzhantel Curl · Core: Hollow Rocks 3×15 — 4×8 / 4×10 / 3×10 / 3×15 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('5×5 Ganzkörper C', 'krafttraining', 35, '{barbell,dumbbell}', 'Maximalkraft: 1. Squat (Langhantel oder Goblet, schwer) · 2. Deadlift (Langhantel oder Kurzhantel, schwer) · 3. Kurzhantel Row (schwer) · 4. Kurzhantel Bench Press (schwer) · Core: Dead Bug 3×10 — 5×5 je Übung · Pause: 3 Min', 'krafttraining', true),
  ('Ganzkörper N', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Kurzhantel Squat · 2. Kurzhantel Bench Press · 3. Kurzhantel Romanian Deadlift · 4. Kurzhantel Row · 5. Kurzhantel Curl · 6. Tricep Extension · Core: Hollow Hold 3×30s — 4×8 je Übung · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper G', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel) · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Goblet Squat · 5. Kurzhantel Curl · Core: Bird Dog 3×10 — 4×6 / 4×8 / 4×10 / 3×10 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Ganzkörper O', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Romanian Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · Core: Bird Dog 3×10 — 4×10 / 4×10 / 4×8 / 4×10 / 3×10 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper P', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Kurzhantel Bench Press · 3. Hip Thrust · 4. Kurzhantel Row · 5. Kurzhantel Curl · Core: V-Ups 3×15 — 4×8 / 4×8 / 3×15 / 4×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper H', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Kurzhantel Overhead Press · 3. Kurzhantel Row · 4. Reverse Lunge · 5. Kurzhantel Curl · Core: Plank 3×45s — 4×8 / 4×8 / 4×10 / 3×12 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Volumen Ganzkörper', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Kurzhantel Squat · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Kurzhantel Overhead Press · 5. Kurzhantel Curl · 6. Tricep Extension · Core: Dead Bug 3×10 — 4×12 je Übung · Pause: 60s', 'krafttraining', true),
  ('Ganzkörper Q', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Kurzhantel Deadlift · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Goblet Squat · 5. Lateral Raise · Core: Dead Bug 3×10 — 4×10 / 4×8 / 4×10 / 3×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper I', 'krafttraining', 35, '{dumbbell,kettlebell}', 'Ganzkörper: 1. Kettlebell Swing · 2. Goblet Squat · 3. Kurzhantel Row · 4. Kurzhantel Press · 5. Push-ups · Core: V-Ups 3×15 — 4×15 / 4×10 / 4×10 / 3×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper R', 'krafttraining', 35, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Kurzhantel Overhead Press · 3. Kurzhantel Romanian Deadlift · 4. Kurzhantel Row · 5. Kurzhantel Curl · Core: Side Plank 3×30s — 4×8 / 4×8 / 4×10 / 4×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('5×5 Ganzkörper B', 'krafttraining', 35, '{barbell,dumbbell}', 'Maximalkraft: 1. Deadlift (Langhantel oder Kurzhantel, schwer) · 2. Squat (Langhantel oder Goblet, schwer) · 3. Kurzhantel Bench Press (schwer) · Core: Plank 3×45s — 5×5 je Übung · Pause: 2–3 Min', 'krafttraining', true),
  ('Ganzkörper J', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Romanian Deadlift · 2. Kurzhantel Bench Press · 3. Kurzhantel Squat · 4. Kurzhantel Row · 5. Lateral Raise · Core: Dead Bug 3×10 — 4×8 / 4×8 / 4×10 / 4×10 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper S', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Hip Thrust · 5. Kurzhantel Overhead Press · 6. Kurzhantel Curl · Core: Hollow Rocks 3×15 — 4×10 / 4×8 / 4×10 / 3×15 / 3×10 / 3×12 · Pause: 90s', 'krafttraining', true),
  ('Ganzkörper K', 'krafttraining', 35, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat (schwer) · 2. Kurzhantel Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · Core: V-Ups 3×15 — 4×8 (schwer) je Übung · Pause: 2 Min', 'krafttraining', true),
  ('Ganzkörper Push/Pull', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Deadlift (Langhantel oder Kurzhantel) · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Kurzhantel Curl · 7. Tricep Extension · Core: Plank 3×45s + V-Ups 3×15 — 4×8 / 4×6 / 4×8 / 4×10 / 3×10 / 3×12 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Oberkörper Komplett', 'krafttraining', 52, '{dumbbell}', 'Oberkörper + Core: 1. Kurzhantel Bench Press · 2. Kurzhantel Incline Press · 3. Kurzhantel Fly · 4. Kurzhantel Row · 5. Kurzhantel Reverse Fly · 6. Kurzhantel Overhead Press · 7. Kurzhantel Curl · 8. Tricep Extension · Core: Hollow Hold 3×30s — 4×8 / 3×10 / 3×12 / 4×10 / 3×12 / 3×10 / 3×12 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Unterkörper Komplett', 'krafttraining', 52, '{barbell,dumbbell}', 'Unterkörper + Core: 1. Squat (Langhantel oder Goblet) · 2. Romanian Deadlift · 3. Lunge · 4. Step-up · 5. Hip Thrust · 6. Calf Raise · Core: Dead Bug 3×10 + Side Plank 3×30s — 4×8 / 4×10 / 4×12 / 3×10 / 4×15 / 4×20 · Pause: 90–120s', 'krafttraining', true),
  ('Ganzkörper Volumen', 'krafttraining', 52, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Kurzhantel Curl · 7. Lateral Raise · Core: Plank 3×45s + Hollow Rocks 3×15 — 4×10 / 4×8 / 4×8 / 4×10 / 3×10 / 3×12 / 3×15 · Pause: 90s', 'krafttraining', true),
  ('5×5 Komplett', 'krafttraining', 52, '{barbell,dumbbell}', 'Maximalkraft + Volumen: 1. Squat (Langhantel oder Goblet, schwer) · 2. Deadlift (Langhantel oder Kurzhantel, schwer) · 3. Kurzhantel Row (schwer) · 4. Kurzhantel Bench Press (schwer) · 5. Kurzhantel Overhead Press (mittel) · 6. Kurzhantel Curl · Core: Hollow Rocks 3×20 — 5×5 (1–4) / 4×8 (5) / 3×12 (6) · Pause: 2–3 Min (1–4), 90s (5–6)', 'krafttraining', true),
  ('Ganzkörper Push/Pull C', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel) · 2. Goblet Squat · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Hip Thrust · 7. Kurzhantel Curl · Core: Hollow Hold 3×30s — 4×8 / 4×8 / 4×8 / 4×10 / 3×10 / 3×15 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Ganzkörper Komplett C', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Kurzhantel Romanian Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Kurzhantel Curl · 7. Tricep Extension · Core: Plank 3×45s + Dead Bug 3×10 — 4×8 / 4×10 / 4×8 / 4×10 / 3×10 / 3×12 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Ganzkörper Push/Pull B', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Deadlift (Langhantel oder Kurzhantel, schwer) · 2. Langhantel oder Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Kurzhantel Overhead Press · 5. Goblet Squat · 6. Kurzhantel Curl · 7. Tricep Extension · Core: V-Ups 3×20 + Side Plank 3×30s — 4×6 / 4×8 / 4×10 / 3×10 / 4×10 / 3×12 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('Ganzkörper Kraft A', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet, schwer) · 2. Deadlift (Langhantel oder Kurzhantel, schwer) · 3. Kurzhantel Row · 4. Kurzhantel Bench Press · 5. Hip Thrust · 6. Kurzhantel Overhead Press · Core: Plank 3×60s — 4×6 (1–2) / 4×8 (3–4) / 3×15 (5) / 3×10 (6) · Pause: 2–3 Min (1–2), 90s (3–6)', 'krafttraining', true),
  ('Ganzkörper Volumen B', 'krafttraining', 52, '{dumbbell}', 'Ganzkörper: 1. Kurzhantel Squat · 2. Kurzhantel Romanian Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Lateral Raise · 7. Kurzhantel Curl · Core: V-Ups 3×20 + Hollow Hold 3×30s — 4×12 je Übung · Pause: 60–75s', 'krafttraining', true),
  ('Ganzkörper Maximalkraft A', 'krafttraining', 52, '{barbell,dumbbell}', 'Maximalkraft: 1. Squat (Langhantel oder Goblet, schwer) · 2. Deadlift (Langhantel oder Kurzhantel, schwer) · 3. Kurzhantel Bench Press (schwer) · 4. Kurzhantel Row (schwer) · 5. Kurzhantel Overhead Press (schwer) · Core: Plank 3×60s — 5×5 je Übung · Pause: 3 Min', 'krafttraining', true),
  ('Ganzkörper Komplett B', 'krafttraining', 52, '{barbell,dumbbell}', 'Ganzkörper: 1. Squat (Langhantel oder Goblet) · 2. Deadlift (Langhantel oder Kurzhantel) · 3. Kurzhantel Bench Press · 4. Kurzhantel Row · 5. Kurzhantel Overhead Press · 6. Hip Thrust · 7. Calf Raise · 8. Kurzhantel Curl · Core: Dead Bug 3×10 + Side Plank 3×30s — 4×8 / 4×8 / 4×8 / 4×10 / 3×10 / 3×15 / 4×20 / 3×12 · Pause: 90–120s', 'krafttraining', true),
  ('5×5 Ganzkörper D', 'krafttraining', 52, '{barbell,dumbbell}', 'Maximalkraft: 1. Deadlift (Langhantel oder Kurzhantel, schwer) · 2. Squat (Langhantel oder Goblet, schwer) · 3. Kurzhantel Bench Press (schwer) · 4. Kurzhantel Row (schwer) · 5. Kurzhantel Overhead Press (mittel) · Core: Hollow Rocks 3×20 — 5×5 (1–4) / 4×8 (5) · Pause: 3 Min (1–4), 90s (5)', 'krafttraining', true),
  ('Ganzkörper Hypertrophie B', 'krafttraining', 52, '{dumbbell}', 'Ganzkörper: 1. Goblet Squat · 2. Kurzhantel Romanian Deadlift · 3. Kurzhantel Bench Press · 4. Kurzhantel Incline Press · 5. Kurzhantel Row · 6. Kurzhantel Overhead Press · 7. Kurzhantel Curl · 8. Tricep Extension · Core: V-Ups 3×15 + Plank 3×45s — 3×12 je Übung · Pause: 60s', 'krafttraining', true),
  ('Ganzkörper Hypertrophie', 'krafttraining', 52, '{dumbbell}', 'Ganzkörper: 1. Kurzhantel Squat · 2. Kurzhantel Bench Press · 3. Kurzhantel Row · 4. Kurzhantel Overhead Press · 5. Kurzhantel Romanian Deadlift · 6. Kurzhantel Curl · 7. Lateral Raise · 8. Tricep Extension · Core: Dead Bug 3×10 + V-Ups 3×20 — 4×10–12 je Übung · Pause: 60–75s', 'krafttraining', true)
ON CONFLICT (name) DO NOTHING;

-- Total: 183 WODs
-- hiit: 60
-- kraft_ausdauer: 50
-- kraft_wenig_zeit: 30
-- krafttraining: 43
